use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionMessageCustomToolCallCustom : The custom tool that the model called.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionMessageCustomToolCallCustom {
    /// The name of the custom tool to call.
    #[serde(rename = "name")]
    pub name: String,
    /// The input for the custom tool call generated by the model.
    #[serde(rename = "input")]
    pub input: String,
}

impl ChatCompletionMessageCustomToolCallCustom {
    /// The custom tool that the model called.
    pub fn new(name: String, input: String) -> ChatCompletionMessageCustomToolCallCustom {
        ChatCompletionMessageCustomToolCallCustom { name, input }
    }
}

/// ChatCompletionMessageCustomToolCall : A call to a custom tool created by the model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionMessageCustomToolCall {
    /// The ID of the tool call.
    #[serde(rename = "id")]
    pub id: String,
    /// The type of the tool. Always `custom`.
    #[serde(rename = "type")]
    pub r#type: ChatCompletionMessageCustomToolCallType,
    #[serde(rename = "custom")]
    pub custom: Box<models::ChatCompletionMessageCustomToolCallCustom>,
}

impl ChatCompletionMessageCustomToolCall {
    /// A call to a custom tool created by the model.
    pub fn new(
        id: String,
        r#type: ChatCompletionMessageCustomToolCallType,
        custom: models::ChatCompletionMessageCustomToolCallCustom,
    ) -> ChatCompletionMessageCustomToolCall {
        ChatCompletionMessageCustomToolCall { id, r#type, custom: Box::new(custom) }
    }
}
/// The type of the tool. Always `custom`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ChatCompletionMessageCustomToolCallType {
    #[serde(rename = "custom")]
    #[default]
    Custom,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChatCompletionMessageListDataInnerAllOfContentPartsInner {
    ChatCompletionRequestMessageContentPartText(
        Box<models::ChatCompletionRequestMessageContentPartText>,
    ),
    ChatCompletionRequestMessageContentPartImage(
        Box<models::ChatCompletionRequestMessageContentPartImage>,
    ),
}

impl Default for ChatCompletionMessageListDataInnerAllOfContentPartsInner {
    fn default() -> Self {
        Self::ChatCompletionRequestMessageContentPartText(Default::default())
    }
}
/// The type of the content part.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ChatCompletionMessageListDataInnerAllOfContentPartsInnerType {
    #[serde(rename = "text")]
    #[default]
    Text,
    #[serde(rename = "image_url")]
    ImageUrl,
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionMessageListDataInner {
    /// The contents of the message.
    #[serde(rename = "content")]
    pub content: String,
    /// The refusal message generated by the model.
    #[serde(rename = "refusal")]
    pub refusal: String,
    /// The role of the author of this message.
    #[serde(rename = "role")]
    pub role: ChatCompletionMessageRole,
    /// The identifier of the chat message.
    #[serde(rename = "id")]
    pub id: String,
    /// The tool calls generated by the model, such as function calls.
    #[serde(rename = "tool_calls", skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<models::ChatCompletionMessageToolCallsInner>>,
    /// Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat).
    #[serde(rename = "annotations", skip_serializing_if = "Option::is_none")]
    pub annotations: Option<Vec<models::ChatCompletionResponseMessageAnnotationsInner>>,
    #[serde(rename = "function_call", skip_serializing_if = "Option::is_none")]
    pub function_call: Option<Box<models::ChatCompletionResponseMessageFunctionCall>>,
    #[serde(
        rename = "audio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub audio: Option<Option<Box<models::ChatCompletionResponseMessageAudio>>>,
    /// If a content parts array was provided, this is an array of `text` and `image_url` parts. Otherwise, null.
    #[serde(
        rename = "content_parts",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content_parts:
        Option<Option<Vec<models::ChatCompletionMessageListDataInnerAllOfContentPartsInner>>>,
}

impl ChatCompletionMessageListDataInner {
    pub fn new(
        content: String,
        refusal: String,
        role: ChatCompletionMessageRole,
        id: String,
    ) -> ChatCompletionMessageListDataInner {
        ChatCompletionMessageListDataInner {
            content,
            refusal,
            role,
            id,
            tool_calls: None,
            annotations: None,
            function_call: None,
            audio: None,
            content_parts: None,
        }
    }
}
/// The role of the author of this message.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ChatCompletionMessageRole {
    #[serde(rename = "assistant")]
    #[default]
    Assistant,
}

/// ChatCompletionMessageList : An object representing a list of chat completion messages.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionMessageList {
    /// The type of this object. It is always set to \"list\".
    #[serde(rename = "object")]
    pub object: ChatCompletionMessageObject,
    /// An array of chat completion message objects.
    #[serde(rename = "data")]
    pub data: Vec<models::ChatCompletionMessageListDataInner>,
    /// The identifier of the first chat message in the data array.
    #[serde(rename = "first_id")]
    pub first_id: String,
    /// The identifier of the last chat message in the data array.
    #[serde(rename = "last_id")]
    pub last_id: String,
    /// Indicates whether there are more chat messages available.
    #[serde(rename = "has_more")]
    pub has_more: bool,
}

impl ChatCompletionMessageList {
    /// An object representing a list of chat completion messages.
    pub fn new(
        object: ChatCompletionMessageObject,
        data: Vec<models::ChatCompletionMessageListDataInner>,
        first_id: String,
        last_id: String,
        has_more: bool,
    ) -> ChatCompletionMessageList {
        ChatCompletionMessageList { object, data, first_id, last_id, has_more }
    }
}
/// The type of this object. It is always set to \"list\".
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ChatCompletionMessageObject {
    #[serde(rename = "list")]
    #[default]
    List,
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionMessageToolCallChunkFunction {
    /// The name of the function to call.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    #[serde(rename = "arguments", skip_serializing_if = "Option::is_none")]
    pub arguments: Option<String>,
}

impl ChatCompletionMessageToolCallChunkFunction {
    pub fn new() -> ChatCompletionMessageToolCallChunkFunction {
        ChatCompletionMessageToolCallChunkFunction { name: None, arguments: None }
    }
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionMessageToolCallChunk {
    #[serde(rename = "index")]
    pub index: i32,
    /// The ID of the tool call.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The type of the tool. Currently, only `function` is supported.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<ChatCompletionMessageToolCallChunkType>,
    #[serde(rename = "function", skip_serializing_if = "Option::is_none")]
    pub function: Option<Box<models::ChatCompletionMessageToolCallChunkFunction>>,
}

impl ChatCompletionMessageToolCallChunk {
    pub fn new(index: i32) -> ChatCompletionMessageToolCallChunk {
        ChatCompletionMessageToolCallChunk { index, id: None, r#type: None, function: None }
    }
}
/// The type of the tool. Currently, only `function` is supported.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ChatCompletionMessageToolCallChunkType {
    #[serde(rename = "function")]
    #[default]
    Function,
}

/// ChatCompletionMessageToolCallFunction : The function that the model called.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionMessageToolCallFunction {
    /// The name of the function to call.
    #[serde(rename = "name")]
    pub name: String,
    /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    #[serde(rename = "arguments")]
    pub arguments: String,
}

impl ChatCompletionMessageToolCallFunction {
    /// The function that the model called.
    pub fn new(name: String, arguments: String) -> ChatCompletionMessageToolCallFunction {
        ChatCompletionMessageToolCallFunction { name, arguments }
    }
}

/// ChatCompletionMessageToolCall : A call to a function tool created by the model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionMessageToolCall {
    /// The ID of the tool call.
    #[serde(rename = "id")]
    pub id: String,
    /// The type of the tool. Currently, only `function` is supported.
    #[serde(rename = "type")]
    pub r#type: ChatCompletionMessageToolCallType,
    #[serde(rename = "function")]
    pub function: Box<models::ChatCompletionMessageToolCallFunction>,
}

impl ChatCompletionMessageToolCall {
    /// A call to a function tool created by the model.
    pub fn new(
        id: String,
        r#type: ChatCompletionMessageToolCallType,
        function: models::ChatCompletionMessageToolCallFunction,
    ) -> ChatCompletionMessageToolCall {
        ChatCompletionMessageToolCall { id, r#type, function: Box::new(function) }
    }
}
/// The type of the tool. Currently, only `function` is supported.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ChatCompletionMessageToolCallType {
    #[serde(rename = "function")]
    #[default]
    Function,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChatCompletionMessageToolCallsInner {
    ChatCompletionMessageToolCall(Box<models::ChatCompletionMessageToolCall>),
    ChatCompletionMessageCustomToolCall(Box<models::ChatCompletionMessageCustomToolCall>),
}

impl Default for ChatCompletionMessageToolCallsInner {
    fn default() -> Self {
        Self::ChatCompletionMessageToolCall(Default::default())
    }
}
