use crate::openai::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionResponseMessageAnnotationsInner : A URL citation when using web search.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessageAnnotationsInner {
    /// The type of the URL citation. Always `url_citation`.
    #[serde(rename = "type")]
    pub r#type: ChatCompletionResponseMessageType,
    #[serde(rename = "url_citation")]
    pub url_citation: Box<models::ChatCompletionResponseMessageAnnotationsInnerUrlCitation>,
}

impl ChatCompletionResponseMessageAnnotationsInner {
    /// A URL citation when using web search.
    pub fn new(
        r#type: ChatCompletionResponseMessageType,
        url_citation: models::ChatCompletionResponseMessageAnnotationsInnerUrlCitation,
    ) -> ChatCompletionResponseMessageAnnotationsInner {
        ChatCompletionResponseMessageAnnotationsInner {
            r#type,
            url_citation: Box::new(url_citation),
        }
    }
}
/// The type of the URL citation. Always `url_citation`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ChatCompletionResponseMessageType {
    #[serde(rename = "url_citation")]
    #[default]
    UrlCitation,
}

/// ChatCompletionResponseMessageAudio : If the audio output modality is requested, this object contains data about the audio response from the model. [Learn more](/docs/guides/audio).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessageAudio {
    /// Unique identifier for this audio response.
    #[serde(rename = "id")]
    pub id: String,
    /// The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the server for use in multi-turn conversations.
    #[serde(rename = "expires_at")]
    pub expires_at: i32,
    /// Base64 encoded audio bytes generated by the model, in the format specified in the request.
    #[serde(rename = "data")]
    pub data: String,
    /// Transcript of the audio generated by the model.
    #[serde(rename = "transcript")]
    pub transcript: String,
}

impl ChatCompletionResponseMessageAudio {
    /// If the audio output modality is requested, this object contains data about the audio response from the model. [Learn more](/docs/guides/audio).
    pub fn new(
        id: String,
        expires_at: i32,
        data: String,
        transcript: String,
    ) -> ChatCompletionResponseMessageAudio {
        ChatCompletionResponseMessageAudio { id, expires_at, data, transcript }
    }
}

/// ChatCompletionResponseMessageFunctionCall : Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessageFunctionCall {
    /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    #[serde(rename = "arguments")]
    pub arguments: String,
    /// The name of the function to call.
    #[serde(rename = "name")]
    pub name: String,
}

impl ChatCompletionResponseMessageFunctionCall {
    /// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
    pub fn new(arguments: String, name: String) -> ChatCompletionResponseMessageFunctionCall {
        ChatCompletionResponseMessageFunctionCall { arguments, name }
    }
}

/// ChatCompletionResponseMessageAnnotationsInnerUrlCitation : A URL citation when using web search.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessageAnnotationsInnerUrlCitation {
    /// The index of the last character of the URL citation in the message.
    #[serde(rename = "end_index")]
    pub end_index: i32,
    /// The index of the first character of the URL citation in the message.
    #[serde(rename = "start_index")]
    pub start_index: i32,
    /// The URL of the web resource.
    #[serde(rename = "url")]
    pub url: String,
    /// The title of the web resource.
    #[serde(rename = "title")]
    pub title: String,
}

impl ChatCompletionResponseMessageAnnotationsInnerUrlCitation {
    /// A URL citation when using web search.
    pub fn new(
        end_index: i32,
        start_index: i32,
        url: String,
        title: String,
    ) -> ChatCompletionResponseMessageAnnotationsInnerUrlCitation {
        ChatCompletionResponseMessageAnnotationsInnerUrlCitation {
            end_index,
            start_index,
            url,
            title,
        }
    }
}

/// ChatCompletionResponseMessage : A chat completion message generated by the model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessage {
    /// The contents of the message.
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<String>,
    /// The refusal message generated by the model.
    #[serde(rename = "refusal", deserialize_with = "Option::deserialize")]
    pub refusal: Option<String>,
    /// The role of the author of this message.
    #[serde(rename = "role")]
    pub role: Role,
    /// The tool calls generated by the model, such as function calls.
    #[serde(rename = "tool_calls", skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<models::ChatCompletionMessageToolCallsInner>>,
    /// Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat).
    #[serde(rename = "annotations", skip_serializing_if = "Option::is_none")]
    pub annotations: Option<Vec<models::ChatCompletionResponseMessageAnnotationsInner>>,
    #[serde(rename = "function_call", skip_serializing_if = "Option::is_none")]
    pub function_call: Option<Box<models::ChatCompletionResponseMessageFunctionCall>>,
    #[serde(
        rename = "audio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub audio: Option<Option<Box<models::ChatCompletionResponseMessageAudio>>>,
}

impl ChatCompletionResponseMessage {
    /// A chat completion message generated by the model.
    pub fn new(
        content: Option<String>,
        refusal: Option<String>,
        role: Role,
    ) -> ChatCompletionResponseMessage {
        ChatCompletionResponseMessage {
            content,
            refusal,
            role,
            tool_calls: None,
            annotations: None,
            function_call: None,
            audio: None,
        }
    }
}
/// The role of the author of this message.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Role {
    #[serde(rename = "assistant")]
    #[default]
    Assistant,
}
