use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionStreamOptions : Options for streaming response. Only set this when you set `stream: true`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionStreamOptions {
    /// If set, an additional chunk will be streamed before the `data: [DONE]` message. The `usage` field on this chunk shows the token usage statistics for the entire request, and the `choices` field will always be an empty array.  All other chunks will also include a `usage` field, but with a null value. **NOTE:** If the stream is interrupted, you may not receive the final usage chunk which contains the total token usage for the request.
    #[serde(rename = "include_usage", skip_serializing_if = "Option::is_none")]
    pub include_usage: Option<bool>,
    /// When true, stream obfuscation will be enabled. Stream obfuscation adds random characters to an `obfuscation` field on streaming delta events to normalize payload sizes as a mitigation to certain side-channel attacks. These obfuscation fields are included by default, but add a small amount of overhead to the data stream. You can set `include_obfuscation` to false to optimize for bandwidth if you trust the network links between your application and the OpenAI API.
    #[serde(rename = "include_obfuscation", skip_serializing_if = "Option::is_none")]
    pub include_obfuscation: Option<bool>,
}

impl ChatCompletionStreamOptions {
    /// Options for streaming response. Only set this when you set `stream: true`.
    pub fn new() -> ChatCompletionStreamOptions {
        ChatCompletionStreamOptions { include_usage: None, include_obfuscation: None }
    }
}

/// ChatCompletionStreamResponseDeltaFunctionCall : Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionStreamResponseDeltaFunctionCall {
    /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    #[serde(rename = "arguments", skip_serializing_if = "Option::is_none")]
    pub arguments: Option<String>,
    /// The name of the function to call.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ChatCompletionStreamResponseDeltaFunctionCall {
    /// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
    pub fn new() -> ChatCompletionStreamResponseDeltaFunctionCall {
        ChatCompletionStreamResponseDeltaFunctionCall { arguments: None, name: None }
    }
}

/// ChatCompletionStreamResponseDelta : A chat completion delta generated by streamed model responses.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionStreamResponseDelta {
    /// The contents of the chunk message.
    #[serde(
        rename = "content",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content: Option<Option<String>>,
    #[serde(rename = "function_call", skip_serializing_if = "Option::is_none")]
    pub function_call: Option<Box<models::ChatCompletionStreamResponseDeltaFunctionCall>>,
    #[serde(rename = "tool_calls", skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<models::ChatCompletionMessageToolCallChunk>>,
    /// The role of the author of this message.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<ChatCompletionStreamRole>,
    /// The refusal message generated by the model.
    #[serde(
        rename = "refusal",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub refusal: Option<Option<String>>,
}

impl ChatCompletionStreamResponseDelta {
    /// A chat completion delta generated by streamed model responses.
    pub fn new() -> ChatCompletionStreamResponseDelta {
        ChatCompletionStreamResponseDelta {
            content: None,
            function_call: None,
            tool_calls: None,
            role: None,
            refusal: None,
        }
    }
}
/// The role of the author of this message.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum ChatCompletionStreamRole {
    #[serde(rename = "developer")]
    #[default]
    Developer,
    #[serde(rename = "system")]
    System,
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
    #[serde(rename = "tool")]
    Tool,
}

