import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./v1.d.ts"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:3000/",
});


const api = createClient(fetchClient);

export default api;