/**
 * Main API entry point
 *
 * Re-exports all API functionality
 */

import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./v1.d.ts"; // generated by openapi-typescript
import { getApiConfig } from "./config";
import { errorMiddleware } from "./errors";

// Get API configuration from environment
const config = getApiConfig();

const fetchClient = createFetchClient<paths>({
  baseUrl: config.baseUrl,
});

// Register error middleware
fetchClient.use(errorMiddleware);

const api = createClient(fetchClient);

// Export default API client
export default api;
export const apiFetch = fetchClient;

// Export types
export type { paths } from './v1.d.ts';

// Export error handling
export {
  ApiError,
  errorMiddleware,
  getErrorMessage,
  getErrorCode,
  isApiError,
} from './errors';
export type { ApiErrorResponse } from './errors';

// Export configuration
export { getApiConfig, getApiBaseUrlAsync, detectApiMode } from './config';
export type { ApiMode } from './config';

// Export diagnostics
export {
  initDiagnostics,
  setDiagnosticsConfig,
  getDiagnosticsConfig,
  logDebug,
  logInfo,
  logWarn,
  logError,
  getLogs,
  getLogsByType,
  getLogsByLevel,
  clearLogs,
  exportLogs,
  getDiagnosticSummary,
  testApiConnectivity,
  logTaskId,
  logTaskStatus,
  verifyApiConfig,
  createDiagnosticReport,
  type DiagnosticEntry,
  type LogLevel,
  type DiagnosticsConfig,
} from './diagnostics';
