/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/backends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all registered backends and their status (`GET /admin/backends`). */
        get: operations["list_backends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/backends/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download a backend shared library from a GitHub release (`POST /admin/backends/download`). */
        post: operations["download_lib"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/backends/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reload a backend with a new shared library path (`POST /admin/backends/reload`). */
        post: operations["reload_lib"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/backends/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get status of a model backend (`GET /admin/backends/status`). */
        get: operations["backend_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/config/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config_value"];
        put: operations["set_config_value"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_models"];
        put?: never;
        post: operations["create_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_model"];
        post?: never;
        delete: operations["delete_model"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Heartbeat endpoint.
         * @description Returns `{"status": "ok", "version": "..."}` with HTTP 200.
         *     Load-balancers and monitoring systems should poll this endpoint.
         */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/transcriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Speech-to-text transcription (`POST /v1/audio/transcriptions`). */
        post: operations["transcribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OpenAI chat completions (`POST /v1/chat/completions`). */
        post: operations["chat_completions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chat_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ffmpeg/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["convert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Image generation (`POST /v1/images/generations`). */
        post: operations["generate_images"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the files available in a HuggingFace model repo (`GET /v1/models/available?repo_id=...`). */
        get: operations["list_available_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download a model file from HuggingFace (`POST /v1/models/download`). */
        post: operations["download_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load (or hot-reload) a model (`POST /v1/models/load`). */
        post: operations["load_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch the loaded model to a different weights file (`POST /v1/models/switch`). */
        post: operations["switch_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/unload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unload the currently loaded model (`POST /v1/models/unload`). */
        post: operations["unload_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_sessions"];
        put?: never;
        post: operations["create_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_session_messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/gpu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["gpu_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_task"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restart_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_task_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response body for list backends endpoint. */
        BackendListResponse: {
            backends: components["schemas"]["BackendStatusResponse"][];
        };
        /** @description Response body for load / status endpoints. */
        BackendStatusResponse: {
            /** @description Backend identifier, e.g. `"ggml.llama"`. */
            backend: string;
            /** @description Human-readable status string. */
            status: string;
        };
        /** @description Path parameters for model-management routes. */
        BackendTypeQuery: {
            /** @description One of `"ggml.llama"`, `"ggml.whisper"`, or `"ggml.diffusion"`. */
            backend_id: string;
        };
        /** @description A single choice in the completion response. */
        ChatChoice: {
            /** @description Why generation stopped (`"stop"`, `"length"`, …). */
            finish_reason: string;
            /**
             * Format: int32
             * @description Zero-based index of this choice.
             */
            index: number;
            /** @description The generated message. */
            message: components["schemas"]["ChatMessage"];
        };
        /** @description Request body for `POST /v1/chat/completions`. */
        ChatCompletionRequest: {
            /** @description Optional chat session ID for stateful conversations. */
            id?: string | null;
            /**
             * Format: int32
             * @description Maximum tokens to generate.
             */
            max_tokens?: number | null;
            /** @description Conversation history; the last user message is used as the prompt. */
            messages: components["schemas"]["ChatMessage"][];
            /**
             * @description The model identifier to use. It can be:
             *     - local model id from `/v1/models`
             *     - cloud model option id from `GET /v1/chat/models`
             */
            model: string;
            /** @description When `true`, the response is streamed token-by-token using SSE. */
            stream?: boolean;
            /**
             * Format: float
             * @description Sampling temperature in [0, 2].
             */
            temperature?: number | null;
        };
        /** @description Response body for `POST /v1/chat/completions`. */
        ChatCompletionResponse: {
            /** @description Generated choices. */
            choices: components["schemas"]["ChatChoice"][];
            /**
             * Format: int64
             * @description Unix timestamp of when the response was created.
             */
            created: number;
            /** @description Unique identifier for this completion. */
            id: string;
            /** @description Model that produced the completion. */
            model: string;
            /** @description Always `"chat.completion"`. */
            object: string;
        };
        /** @description A single message in the conversation history. */
        ChatMessage: {
            /** @description The content of the message. */
            content: string;
            /** @description The role of the message author (`"system"`, `"user"`, `"assistant"`). */
            role: string;
        };
        /** @description A selectable chat model option from `GET /v1/chat/models`. */
        ChatModelOption: {
            /** @description Backend id when `source = local`, e.g. `ggml.llama`. */
            backend_id?: string | null;
            /** @description User-facing display label. */
            display_name: string;
            /** @description Whether model artifacts are already downloaded locally. */
            downloaded: boolean;
            /** @description Stable option id used in `POST /v1/chat/completions`. */
            id: string;
            /** @description Whether a model download task is running. */
            pending: boolean;
            /** @description Cloud provider id when `source = cloud`. */
            provider_id?: string | null;
            /** @description Cloud provider name when `source = cloud`. */
            provider_name?: string | null;
            /** @description Whether this option is local or cloud. */
            source: components["schemas"]["ChatModelSource"];
        };
        /**
         * @description Chat model source type.
         * @enum {string}
         */
        ChatModelSource: "local" | "cloud";
        CompletionRequest: {
            decode?: null | components["schemas"]["TranscribeDecodeRequest"];
            /** @description The audio file path to transcribe. */
            path: string;
            vad?: null | components["schemas"]["TranscribeVadRequest"];
        };
        ConfigEntry: {
            key: string;
            name: string;
            value: string;
        };
        ConvertRequest: {
            /** @description Desired output format (e.g. `"mp3"`, `"wav"`, `"mp4"`). */
            output_format: string;
            /** @description Optional output path; defaults to source path with new extension. */
            output_path?: string | null;
            /** @description Absolute path to the source file. */
            source_path: string;
        };
        ConvertResponse: {
            task_id: string;
        };
        CreateModelRequest: {
            backend_ids: string[];
            display_name: string;
            filename: string;
            repo_id: string;
        };
        CreateSessionRequest: {
            name?: string | null;
        };
        DownloadLibRequest: {
            /** @description Backend identifier, e.g. `"ggml.llama"`, `"ggml.whisper"`, `"ggml.diffusion"`. */
            backend_id: string;
            /** @description Absolute directory where release assets should be installed. */
            target_dir: string;
        };
        DownloadModelRequest: {
            /** @description Backend identifier to use for this download. */
            backend_id: string;
            /** @description Model catalog entry ID from `/admin/models`. */
            model_id: string;
        };
        /** @description Per-GPU snapshot from `all-smi`. */
        GpuDeviceStatus: {
            /** @description Device class from all-smi, e.g. GPU / NPU. */
            device_type: string;
            /**
             * Format: int32
             * @description Stable GPU index in current snapshot.
             */
            id: number;
            /**
             * Format: double
             * @description Derived VRAM usage percentage (0-100).
             */
            memory_usage_percent: number;
            /** @description Human-readable GPU model name. */
            name: string;
            /**
             * Format: double
             * @description Current power draw in watts.
             */
            power_draw_watts: number;
            /**
             * Format: int32
             * @description Reported temperature in Celsius.
             */
            temperature_celsius: number;
            /**
             * Format: int64
             * @description Total VRAM bytes.
             */
            total_memory_bytes: number;
            /**
             * Format: int64
             * @description Current used VRAM bytes.
             */
            used_memory_bytes: number;
            /**
             * Format: double
             * @description Core utilization in percentage (0-100).
             */
            utilization_percent: number;
        };
        /** @description Aggregated GPU monitor payload for the status bar. */
        GpuStatusResponse: {
            /** @description Whether GPU telemetry is available for this host. */
            available: boolean;
            /** @description Telemetry backend identifier. */
            backend: string;
            /** @description Current GPU list snapshot. */
            devices: components["schemas"]["GpuDeviceStatus"][];
            /** @description Optional reason when telemetry is unavailable. */
            error?: string | null;
            /** @description RFC3339 timestamp generated by server. */
            updated_at: string;
        };
        /** @description Request body for `POST /v1/images/generations`. */
        ImageGenerationRequest: {
            /** @description The model identifier to use. */
            model: string;
            /**
             * Format: int32
             * @description Number of images to generate (default `1`).
             */
            n?: number;
            /** @description Text description of the desired image. */
            prompt: string;
            /** @description Desired image size, e.g. `"512x512"`. */
            size?: string | null;
        };
        /** @description Query parameters for listing files in a HuggingFace repo. */
        ListAvailableQuery: {
            /** @description HuggingFace repo id, e.g. `"bartowski/Qwen2.5-0.5B-Instruct-GGUF"`. */
            repo_id: string;
        };
        /** @description Query parameters for listing catalog models by computed status. */
        ListModelsQuery: {
            status?: components["schemas"]["ModelListStatus"];
        };
        /** @description Request body for `POST /v1/models/load`. */
        LoadModelRequest: {
            /** @description Backend identifier, e.g. `"ggml.llama"`. */
            backend_id: string;
            /** @description Path to the model weights file. */
            model_path: string;
            /**
             * Format: int32
             * @description Optional worker override. If omitted, server uses global config by backend.
             */
            num_workers?: number | null;
        };
        MessageResponse: {
            content: string;
            created_at: string;
            id: string;
            role: string;
            session_id: string;
        };
        /** @description Model catalog entry response with computed download status. */
        ModelCatalogItemResponse: {
            backend_ids: string[];
            display_name: string;
            filename: string;
            id: string;
            /** @description Whether this catalog entry is recognized as a Whisper VAD model candidate. */
            is_vad_model: boolean;
            last_downloaded_at?: string | null;
            local_path?: string | null;
            pending_task_id?: string | null;
            pending_task_status?: string | null;
            repo_id: string;
            status: components["schemas"]["ModelListStatus"];
        };
        ModelCatalogResponse: {
            backend_ids: string[];
            created_at: string;
            display_name: string;
            filename: string;
            id: string;
            last_download_task_id?: string | null;
            last_downloaded_at?: string | null;
            local_path?: string | null;
            repo_id: string;
            updated_at: string;
        };
        /** @enum {string} */
        ModelListStatus: "downloaded" | "pending" | "not_downloaded" | "all";
        /** @description Response body for load / status endpoints. */
        ModelStatusResponse: {
            /** @description Backend identifier, e.g. `"ggml.llama"`. */
            backend: string;
            /** @description Human-readable status string. */
            status: string;
        };
        ReloadLibRequest: {
            backend_id: string;
            lib_path: string;
            model_path: string;
            /** Format: int32 */
            num_workers?: number;
        };
        SessionResponse: {
            created_at: string;
            id: string;
            name: string;
            state_path?: string | null;
            updated_at: string;
        };
        SetConfigBody: {
            name?: string | null;
            value: string;
        };
        SwitchModelRequest: {
            backend_id: string;
            model_path: string;
            /**
             * Format: int32
             * @description Optional worker override. If omitted, server uses global config by backend.
             */
            num_workers?: number | null;
        };
        TaskResponse: {
            created_at: string;
            error_msg?: string | null;
            id: string;
            status: string;
            task_type: string;
            updated_at: string;
        };
        /**
         * @description Result payload returned by `GET /v1/tasks/{id}/result`.
         *
         *     Exactly one field is populated depending on the task type:
         *     - `image` tasks: `image` contains a `data:image/png;base64,…` data URI.
         *     - Text-producing tasks (whisper, etc.): `text` contains the UTF-8 result.
         */
        TaskResultPayload: {
            /** @description Base64-encoded PNG data URI, present for `image` task results. */
            image?: string | null;
            /** @description Text content, present for `whisper` and other text-producing task results. */
            text?: string | null;
        };
        TaskTypeQuery: {
            type?: string | null;
        };
        TranscribeDecodeRequest: {
            /**
             * Format: int32
             * @description Duration in milliseconds to process (0 means full input).
             */
            duration_ms?: number | null;
            /**
             * Format: float
             * @description Entropy threshold.
             */
            entropy_thold?: number | null;
            /**
             * Format: float
             * @description Log probability threshold.
             */
            logprob_thold?: number | null;
            /**
             * Format: int32
             * @description Maximum segment length in characters.
             */
            max_len?: number | null;
            /**
             * Format: int32
             * @description Maximum tokens per segment.
             */
            max_tokens?: number | null;
            /** @description Do not use past transcription as prompt. */
            no_context?: boolean | null;
            /**
             * Format: float
             * @description No-speech threshold.
             */
            no_speech_thold?: number | null;
            /** @description Do not generate timestamps. */
            no_timestamps?: boolean | null;
            /**
             * Format: int32
             * @description Start offset in milliseconds.
             */
            offset_ms?: number | null;
            /** @description Split timestamps on words instead of tokens. */
            split_on_word?: boolean | null;
            /** @description Suppress non-speech tokens. */
            suppress_nst?: boolean | null;
            /** @description Enable tinydiarize speaker turn detection. */
            tdrz_enable?: boolean | null;
            /**
             * Format: float
             * @description Initial decoding temperature.
             */
            temperature?: number | null;
            /**
             * Format: float
             * @description Temperature increment for fallback decoding.
             */
            temperature_inc?: number | null;
            /** @description Enable token-level timestamps. */
            token_timestamps?: boolean | null;
            /**
             * Format: float
             * @description Word timestamp probability threshold.
             */
            word_thold?: number | null;
        };
        TranscribeVadRequest: {
            /** @description Enable VAD during whisper transcription. */
            enabled?: boolean;
            /**
             * Format: float
             * @description Maximum speech segment duration in seconds before auto-splitting.
             */
            max_speech_duration_s?: number | null;
            /**
             * Format: int32
             * @description Minimum silence duration in milliseconds used to split segments.
             */
            min_silence_duration_ms?: number | null;
            /**
             * Format: int32
             * @description Minimum speech segment duration in milliseconds.
             */
            min_speech_duration_ms?: number | null;
            /** @description Absolute path to the VAD model file. */
            model_path?: string | null;
            /**
             * Format: float
             * @description Overlap in seconds between adjacent VAD segments.
             */
            samples_overlap?: number | null;
            /**
             * Format: int32
             * @description Padding in milliseconds added around each detected speech segment.
             */
            speech_pad_ms?: number | null;
            /**
             * Format: float
             * @description Probability threshold used to classify speech.
             */
            threshold?: number | null;
        };
        UpdateModelRequest: {
            backend_ids?: string[] | null;
            display_name?: string | null;
            filename?: string | null;
            repo_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_backends: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all registered backends */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendListResponse"];
                };
            };
            /** @description Unauthorised (admin token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    download_lib: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadLibRequest"];
            };
        };
        responses: {
            /** @description Download task created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad request (invalid path) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorised (management token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reload_lib: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReloadLibRequest"];
            };
        };
        responses: {
            /** @description Backend reloaded with new library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendStatusResponse"];
                };
            };
            /** @description Bad request (invalid path or unknown backend) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorised (management token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    backend_status: {
        parameters: {
            query: {
                /** @description One of `"ggml.llama"`, `"ggml.whisper"`, or `"ggml.diffusion"`. */
                backend_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend worker is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendStatusResponse"];
                };
            };
            /** @description Unknown model type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorised (admin token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all configuration entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEntry"][];
                };
            };
            /** @description Unauthorised (management token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_config_value: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get a configuration entry by key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEntry"];
                };
            };
            /** @description Unauthorised (management token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Config key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_config_value: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetConfigBody"];
            };
        };
        responses: {
            /** @description Set a configuration entry by key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEntry"];
                };
            };
            /** @description Unauthorised (management token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Config key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List model catalog entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalogResponse"][];
                };
            };
            /** @description Unauthorised (management token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModelRequest"];
            };
        };
        responses: {
            /** @description Model catalog entry created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalogResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorised (management token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateModelRequest"];
            };
        };
        responses: {
            /** @description Model catalog entry updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalogResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorised (management token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Model not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model catalog entry deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorised (management token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Model not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    transcribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Audio transcription request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionRequest"];
            };
        };
        responses: {
            /** @description Task accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_completions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Completion generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatCompletionResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_chat_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Selectable chat models (local + cloud providers) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatModelOption"][];
                };
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    convert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConvertRequest"];
            };
        };
        responses: {
            /** @description Conversion task created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvertResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate_images: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageGenerationRequest"];
            };
        };
        responses: {
            /** @description Task accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad request (invalid parameters) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_models: {
        parameters: {
            query?: {
                status?: components["schemas"]["ModelListStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List model catalog entries by download status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalogItemResponse"][];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_available_models: {
        parameters: {
            query: {
                /** @description HuggingFace repo id, e.g. `"bartowski/Qwen2.5-0.5B-Instruct-GGUF"`. */
                repo_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad request (invalid parameters) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    download_model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadModelRequest"];
            };
        };
        responses: {
            /** @description Download task created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad request (invalid parameters) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Model catalog entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    load_model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadModelRequest"];
            };
        };
        responses: {
            /** @description Model load initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatusResponse"];
                };
            };
            /** @description Unknown backend or invalid paths */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorised (management token required) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    switch_model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchModelRequest"];
            };
        };
        responses: {
            /** @description Model switched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatusResponse"];
                };
            };
            /** @description Bad request (invalid parameters) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unload_model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadModelRequest"];
            };
        };
        responses: {
            /** @description Task accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatusResponse"];
                };
            };
            /** @description Bad request (invalid parameters) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session list retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_session_messages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session messages retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"][];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gpu_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current GPU telemetry snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpuStatusResponse"];
                };
            };
        };
    };
    list_tasks: {
        parameters: {
            query?: {
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tasks listed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the task to retrieve */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the task to cancel */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restart_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the task to restart */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_task_result: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the task to retrieve result for */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task result retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResultPayload"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
