use crate::models;
use serde::{Deserialize, Serialize};

/// ApplyPatchToolCallItemParam : A tool call representing a request to create, delete, or update files using diff patches.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyPatchToolCallItemParam {
    /// The type of the item. Always `apply_patch_call`.
    #[serde(rename = "type")]
    pub r#type: ApplyPatchToolCallItemParamType,
    /// The unique ID of the apply patch tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The status of the apply patch tool call. One of `in_progress` or `completed`.
    #[serde(rename = "status")]
    pub status: models::ApplyPatchCallStatusParam,
    /// The specific create, delete, or update instruction for the apply_patch tool call.
    #[serde(rename = "operation")]
    pub operation: Box<models::ApplyPatchOperationParam>,
    /// The unique ID of the apply patch tool call. Populated when this item is returned via API.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
}

impl ApplyPatchToolCallItemParam {
    /// A tool call representing a request to create, delete, or update files using diff patches.
    pub fn new(
        r#type: ApplyPatchToolCallItemParamType,
        call_id: String,
        status: models::ApplyPatchCallStatusParam,
        operation: models::ApplyPatchOperationParam,
    ) -> ApplyPatchToolCallItemParam {
        ApplyPatchToolCallItemParam {
            r#type,
            call_id,
            status,
            operation: Box::new(operation),
            id: None,
        }
    }
}
/// The type of the item. Always `apply_patch_call`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ApplyPatchToolCallItemParamType {
    #[serde(rename = "apply_patch_call")]
    #[default]
    ApplyPatchCall,
}

/// ApplyPatchToolCallOutputItemParam : The streamed output emitted by an apply patch tool call.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyPatchToolCallOutputItemParam {
    /// The type of the item. Always `apply_patch_call_output`.
    #[serde(rename = "type")]
    pub r#type: ApplyPatchToolCallOutputItemParamType,
    /// The unique ID of the apply patch tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The status of the apply patch tool call output. One of `completed` or `failed`.
    #[serde(rename = "status")]
    pub status: models::ApplyPatchCallOutputStatusParam,
    /// The unique ID of the apply patch tool call output. Populated when this item is returned via API.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    /// Optional human-readable log text from the apply patch tool (e.g., patch results or errors).
    #[serde(
        rename = "output",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub output: Option<Option<String>>,
}

impl ApplyPatchToolCallOutputItemParam {
    /// The streamed output emitted by an apply patch tool call.
    pub fn new(
        r#type: ApplyPatchToolCallOutputItemParamType,
        call_id: String,
        status: models::ApplyPatchCallOutputStatusParam,
    ) -> ApplyPatchToolCallOutputItemParam {
        ApplyPatchToolCallOutputItemParam { r#type, call_id, status, id: None, output: None }
    }
}
/// The type of the item. Always `apply_patch_call_output`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ApplyPatchToolCallOutputItemParamType {
    #[serde(rename = "apply_patch_call_output")]
    #[default]
    ApplyPatchCallOutput,
}

/// ApplyPatchToolCallOutput : The output emitted by an apply patch tool call.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyPatchToolCallOutput {
    /// The type of the item. Always `apply_patch_call_output`.
    #[serde(rename = "type")]
    pub r#type: ApplyPatchToolCallOutputType,
    /// The unique ID of the apply patch tool call output. Populated when this item is returned via API.
    #[serde(rename = "id")]
    pub id: String,
    /// The unique ID of the apply patch tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The status of the apply patch tool call output. One of `completed` or `failed`.
    #[serde(rename = "status")]
    pub status: models::ApplyPatchCallOutputStatus,
    /// Optional textual output returned by the apply patch tool.
    #[serde(
        rename = "output",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub output: Option<Option<String>>,
    /// The ID of the entity that created this tool call output.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl ApplyPatchToolCallOutput {
    /// The output emitted by an apply patch tool call.
    pub fn new(
        r#type: ApplyPatchToolCallOutputType,
        id: String,
        call_id: String,
        status: models::ApplyPatchCallOutputStatus,
    ) -> ApplyPatchToolCallOutput {
        ApplyPatchToolCallOutput { r#type, id, call_id, status, output: None, created_by: None }
    }
}
/// The type of the item. Always `apply_patch_call_output`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ApplyPatchToolCallOutputType {
    #[serde(rename = "apply_patch_call_output")]
    #[default]
    ApplyPatchCallOutput,
}

/// ApplyPatchToolCall : A tool call that applies file diffs by creating, deleting, or updating files.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyPatchToolCall {
    /// The type of the item. Always `apply_patch_call`.
    #[serde(rename = "type")]
    pub r#type: ApplyPatchToolCallType,
    /// The unique ID of the apply patch tool call. Populated when this item is returned via API.
    #[serde(rename = "id")]
    pub id: String,
    /// The unique ID of the apply patch tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The status of the apply patch tool call. One of `in_progress` or `completed`.
    #[serde(rename = "status")]
    pub status: models::ApplyPatchCallStatus,
    #[serde(rename = "operation")]
    pub operation: Box<models::ApplyPatchOperation>,
    /// The ID of the entity that created this tool call.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl ApplyPatchToolCall {
    /// A tool call that applies file diffs by creating, deleting, or updating files.
    pub fn new(
        r#type: ApplyPatchToolCallType,
        id: String,
        call_id: String,
        status: models::ApplyPatchCallStatus,
        operation: models::ApplyPatchOperation,
    ) -> ApplyPatchToolCall {
        ApplyPatchToolCall {
            r#type,
            id,
            call_id,
            status,
            operation: Box::new(operation),
            created_by: None,
        }
    }
}

/// The type of the item. Always `apply_patch_call`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ApplyPatchToolCallType {
    #[serde(rename = "apply_patch_call")]
    #[default]
    ApplyPatchCall,
}

/// ApplyPatchToolParam : Allows the assistant to create, delete, or update files using unified diffs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyPatchToolParam {
    /// The type of the tool. Always `apply_patch`.
    #[serde(rename = "type")]
    pub r#type: ApplyPatchToolParamType,
}

impl ApplyPatchToolParam {
    /// Allows the assistant to create, delete, or update files using unified diffs.
    pub fn new(r#type: ApplyPatchToolParamType) -> ApplyPatchToolParam {
        ApplyPatchToolParam { r#type }
    }
}
/// The type of the tool. Always `apply_patch`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ApplyPatchToolParamType {
    #[serde(rename = "apply_patch")]
    #[default]
    ApplyPatch,
}
