use crate::openai::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionRequestAssistantMessageAudio : Data about a previous audio response from the model. [Learn more](/docs/guides/audio).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionRequestAssistantMessageAudio {
    /// Unique identifier for a previous audio response from the model.
    #[serde(rename = "id")]
    pub id: String,
}

impl ChatCompletionRequestAssistantMessageAudio {
    /// Data about a previous audio response from the model. [Learn more](/docs/guides/audio).
    pub fn new(id: String) -> ChatCompletionRequestAssistantMessageAudio {
        ChatCompletionRequestAssistantMessageAudio { id }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChatCompletionRequestAssistantMessageContentPart {
    ChatCompletionRequestMessageContentPartText(
        Box<models::ChatCompletionRequestMessageContentPartText>,
    ),
    ChatCompletionRequestMessageContentPartRefusal(
        Box<models::ChatCompletionRequestMessageContentPartRefusal>,
    ),
}

impl Default for ChatCompletionRequestAssistantMessageContentPart {
    fn default() -> Self {
        Self::ChatCompletionRequestMessageContentPartText(Default::default())
    }
}

/// ChatCompletionRequestAssistantMessageContent : The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.
/// The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChatCompletionRequestAssistantMessageContent {
    /// The contents of the assistant message.
    TextContent(String),
    /// An array of content parts with a defined type. Can be one or more of type `text`, or exactly one of type `refusal`.
    ArrayContentParts(Vec<models::ChatCompletionRequestAssistantMessageContentPart>),
}

impl Default for ChatCompletionRequestAssistantMessageContent {
    fn default() -> Self {
        Self::TextContent(Default::default())
    }
}

/// ChatCompletionRequestAssistantMessage : Messages sent by the model in response to user messages.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionRequestAssistantMessage {
    /// The role of the messages author, in this case `assistant`.
    #[serde(rename = "role")]
    pub role: ChatCompletionRequestRole,
    #[serde(
        rename = "content",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content: Option<Option<Box<models::ChatCompletionRequestAssistantMessageContent>>>,
    /// The refusal message by the assistant.
    #[serde(
        rename = "refusal",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub refusal: Option<Option<String>>,
    /// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(
        rename = "audio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub audio: Option<Option<Box<models::ChatCompletionRequestAssistantMessageAudio>>>,
    /// The tool calls generated by the model, such as function calls.
    #[serde(rename = "tool_calls", skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<models::ChatCompletionMessageToolCallsInner>>,
    #[serde(
        rename = "function_call",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub function_call:
        Option<Option<Box<models::ChatCompletionRequestAssistantMessageFunctionCall>>>,
}

impl ChatCompletionRequestAssistantMessage {
    /// Messages sent by the model in response to user messages.
    pub fn new(role: ChatCompletionRequestRole) -> ChatCompletionRequestAssistantMessage {
        ChatCompletionRequestAssistantMessage {
            role,
            content: None,
            refusal: None,
            name: None,
            audio: None,
            tool_calls: None,
            function_call: None,
        }
    }
}
/// The role of the messages author, in this case `assistant`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ChatCompletionRequestRole {
    #[serde(rename = "assistant")]
    #[default]
    Assistant,
}
