//! Request / response types for system telemetry APIs (`/v1/system/...`).

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Per-GPU snapshot from `all-smi`.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct GpuDeviceStatus {
    /// Stable GPU index in current snapshot.
    pub id: u32,
    /// Human-readable GPU model name.
    pub name: String,
    /// Device class from all-smi, e.g. GPU / NPU.
    pub device_type: String,
    /// Core utilization in percentage (0-100).
    pub utilization_percent: f64,
    /// Reported temperature in Celsius.
    pub temperature_celsius: u32,
    /// Current used VRAM bytes.
    pub used_memory_bytes: u64,
    /// Total VRAM bytes.
    pub total_memory_bytes: u64,
    /// Derived VRAM usage percentage (0-100).
    pub memory_usage_percent: f64,
    /// Current power draw in watts.
    pub power_draw_watts: f64,
}

/// Aggregated GPU monitor payload for the status bar.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct GpuStatusResponse {
    /// Whether GPU telemetry is available for this host.
    pub available: bool,
    /// Telemetry backend identifier.
    pub backend: String,
    /// RFC3339 timestamp generated by server.
    pub updated_at: String,
    /// Current GPU list snapshot.
    pub devices: Vec<GpuDeviceStatus>,
    /// Optional reason when telemetry is unavailable.
    pub error: Option<String>,
}
