pub mod image {
    use crate::models;
    use serde::{Deserialize, Serialize};

    #[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
    pub struct Image {
        /// The base64-encoded JSON of the generated image. Returned by default for the GPT image models, and only present if `response_format` is set to `b64_json` for `dall-e-2` and `dall-e-3`.
        #[serde(rename = "b64_json", skip_serializing_if = "Option::is_none")]
        pub b64_json: Option<String>,
        /// When using `dall-e-2` or `dall-e-3`, the URL of the generated image if `response_format` is set to `url` (default value). Unsupported for the GPT image models.
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        pub url: Option<String>,
        /// For `dall-e-3` only, the revised prompt that was used to generate the image.
        #[serde(rename = "revised_prompt", skip_serializing_if = "Option::is_none")]
        pub revised_prompt: Option<String>,
    }

    impl Image {
        /// Represents the content or the URL of an image generated by the OpenAI API.
        pub fn new() -> Image {
            Image { b64_json: None, url: None, revised_prompt: None }
        }
    }
}

pub mod images_response {
    use crate::models;
    use serde::{Deserialize, Serialize};

    use super::super::edit::Size;
    use super::super::generation::OutputFormat;
    use super::super::generation::Quality;
    use super::background::Background;
    use crate::openai::models::model_types::misc::Summary;
    #[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
    pub struct ImagesResponse {
        /// The Unix timestamp (in seconds) of when the image was created.
        #[serde(rename = "created")]
        pub created: i32,
        /// The list of generated images.
        #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
        pub data: Option<Vec<models::Image>>,
        /// The background parameter used for the image generation. Either `transparent` or `opaque`.
        #[serde(rename = "background", skip_serializing_if = "Option::is_none")]
        pub background: Option<Background>,
        /// The output format of the image generation. Either `png`, `webp`, or `jpeg`.
        #[serde(rename = "output_format", skip_serializing_if = "Option::is_none")]
        pub output_format: Option<OutputFormat>,
        /// The size of the image generated. Either `1024x1024`, `1024x1536`, or `1536x1024`.
        #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
        pub size: Option<Size>,
        /// The quality of the image generated. Either `low`, `medium`, or `high`.
        #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
        pub quality: Option<Quality>,
        #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
        pub usage: Option<Box<models::ImageGenUsage>>,
    }

    impl ImagesResponse {
        /// The response from the image generation endpoint.
        pub fn new(created: i32) -> ImagesResponse {
            ImagesResponse {
                created,
                data: None,
                background: None,
                output_format: None,
                size: None,
                quality: None,
                usage: None,
            }
        }
    }
    // The background parameter used for the image generation. Either `transparent` or `opaque`.
}

pub mod background {
    use crate::models;
    use serde::{Deserialize, Serialize};

    #[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
    pub(crate) enum Background {
        #[serde(rename = "transparent")]
        Transparent,
        #[serde(rename = "opaque")]
        Opaque,
    }

    impl Default for Background {
        fn default() -> Background {
            Self::Transparent
        }
    }
    // The output format of the image generation. Either `png`, `webp`, or `jpeg`.
}

pub(crate) use background::Background;
pub use image::Image;
pub use images_response::ImagesResponse;
