use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Image {
    /// The base64-encoded JSON of the generated image. Returned by default for the GPT image models, and only present if `response_format` is set to `b64_json` for `dall-e-2` and `dall-e-3`.
    #[serde(rename = "b64_json", skip_serializing_if = "Option::is_none")]
    pub b64_json: Option<String>,
    /// When using `dall-e-2` or `dall-e-3`, the URL of the generated image if `response_format` is set to `url` (default value). Unsupported for the GPT image models.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// For `dall-e-3` only, the revised prompt that was used to generate the image.
    #[serde(rename = "revised_prompt", skip_serializing_if = "Option::is_none")]
    pub revised_prompt: Option<String>,
}

impl Image {
    /// Represents the content or the URL of an image generated by the OpenAI API.
    pub fn new() -> Image {
        Image { b64_json: None, url: None, revised_prompt: None }
    }
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImagesResponse {
    /// The Unix timestamp (in seconds) of when the image was created.
    #[serde(rename = "created")]
    pub created: i32,
    /// The list of generated images.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::Image>>,
    /// The background parameter used for the image generation. Either `transparent` or `opaque`.
    #[serde(rename = "background", skip_serializing_if = "Option::is_none")]
    pub background: Option<ImagesResponseBackground>,
    /// The output format of the image generation. Either `png`, `webp`, or `jpeg`.
    #[serde(rename = "output_format", skip_serializing_if = "Option::is_none")]
    pub output_format: Option<ImagesResponseOutputFormat>,
    /// The size of the image generated. Either `1024x1024`, `1024x1536`, or `1536x1024`.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<ImagesResponseSize>,
    /// The quality of the image generated. Either `low`, `medium`, or `high`.
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<ImagesResponseQuality>,
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Box<models::ImageGenUsage>>,
}

impl ImagesResponse {
    /// The response from the image generation endpoint.
    pub fn new(created: i32) -> ImagesResponse {
        ImagesResponse {
            created,
            data: None,
            background: None,
            output_format: None,
            size: None,
            quality: None,
            usage: None,
        }
    }
}

// The background parameter used for the image generation. Either `transparent` or `opaque`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default)]
pub enum ImagesResponseBackground {
    #[serde(rename = "transparent")]
    #[default]
    Transparent,
    #[serde(rename = "opaque")]
    Opaque,
}

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ImagesResponseOutputFormat {
    #[serde(rename = "png")]
    #[default]
    Png,
    #[serde(rename = "webp")]
    Webp,
    #[serde(rename = "jpeg")]
    Jpeg,
}

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ImagesResponseSize {
    #[serde(rename = "1024x1024")]
    #[default]
    Variant1024x1024,
    #[serde(rename = "1024x1536")]
    Variant1024x1536,
    #[serde(rename = "1536x1024")]
    Variant1536x1024,
    #[serde(rename = "auto")]
    Auto,
}

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ImagesResponseQuality {
    #[serde(rename = "low")]
    #[default]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
}
