// GENERATED by `bun run gen:mobile` — do not edit.
// Source of truth: packages/slab-components/src/styles/globals.css.
// Raw oklch strings for every token live in design/tokens.json (wide-gamut upgrade path).

import 'dart:ui' show Color;
import 'package:flutter/animation.dart' show Cubic;

class SlabTokensLight {
  static const Color background = Color(0xFFF7F9FB);
  static const Color foreground = Color(0xFF191C1E);
  static const Color card = Color(0xFFFFFFFF);
  static const Color cardForeground = Color(0xFF191C1E);
  static const Color popover = Color(0xFFFFFFFF);
  static const Color popoverForeground = Color(0xFF191C1E);
  static const Color primary = Color(0xFF0D9488);
  static const Color primaryForeground = Color(0xFFF8FFFD);
  static const Color secondary = Color(0xFFF2F4F6);
  static const Color secondaryForeground = Color(0xFF3D4947);
  static const Color muted = Color(0xFFF2F4F6);
  static const Color mutedForeground = Color(0xFF6D7A77);
  static const Color accent = Color(0xFFEEF2F4);
  static const Color accentForeground = Color(0xFF191C1E);
  static const Color destructive = Color(0xFFEF4444);
  static const Color destructiveForeground = Color(0xFFFFFFFF);
  static const Color border = Color(0xFFE2E8EE);
  static const Color input = Color(0xFFE0E3E5);
  static const Color ring = Color(0xFF0D9488);
  static const Color chart1 = Color(0xFF0D9488);
  static const Color chart2 = Color(0xFF2563EB);
  static const Color chart3 = Color(0xFFF59E0B);
  static const Color chart4 = Color(0xFF8B5CF6);
  static const Color chart5 = Color(0xFFEC4899);
  static const Color sidebar = Color(0xFFF2F4F6);
  static const Color sidebarForeground = Color(0xFF191C1E);
  static const Color sidebarPrimary = Color(0xFF0D9488);
  static const Color sidebarPrimaryForeground = Color(0xFFF8FFFD);
  static const Color sidebarAccent = Color(0xFFFFFFFF);
  static const Color sidebarAccentForeground = Color(0xFF191C1E);
  static const Color sidebarBorder = Color(0xFFE5E7EB);
  static const Color sidebarRing = Color(0xFF0D9488);
  static const Color brandGold = Color(0xFF855300);
  static const Color aiBubble = Color(0xFFE6E8EA);
  static const Color aiBubbleForeground = Color(0xFF191C1E);
  static const Color userBubble = Color(0xFFD5E3FD);
  static const Color userBubbleForeground = Color(0xFF0D1C2F);
  static const Color aiTool = Color(0xFFFFDDB8);
  static const Color aiToolForeground = Color(0xFF855300);
  static const Color success = Color(0xFF059669);
  static const Color successForeground = Color(0xFFF0FDF4);

  /// Field names in declaration order (light/dark parity guard).
  static const List<String> tokenNames = ['background', 'foreground', 'card', 'cardForeground', 'popover', 'popoverForeground', 'primary', 'primaryForeground', 'secondary', 'secondaryForeground', 'muted', 'mutedForeground', 'accent', 'accentForeground', 'destructive', 'destructiveForeground', 'border', 'input', 'ring', 'chart1', 'chart2', 'chart3', 'chart4', 'chart5', 'sidebar', 'sidebarForeground', 'sidebarPrimary', 'sidebarPrimaryForeground', 'sidebarAccent', 'sidebarAccentForeground', 'sidebarBorder', 'sidebarRing', 'brandGold', 'aiBubble', 'aiBubbleForeground', 'userBubble', 'userBubbleForeground', 'aiTool', 'aiToolForeground', 'success', 'successForeground'];
}

class SlabTokensDark {
  static const Color background = Color(0xFF0F1518);
  static const Color foreground = Color(0xFFF3F7F7);
  static const Color card = Color(0xFF151D21);
  static const Color cardForeground = Color(0xFFF3F7F7);
  static const Color popover = Color(0xFF192226);
  static const Color popoverForeground = Color(0xFFF3F7F7);
  static const Color primary = Color(0xFF4CC7BA);
  static const Color primaryForeground = Color(0xFF062321);
  static const Color secondary = Color(0xFF1E2A30);
  static const Color secondaryForeground = Color(0xFFF3F7F7);
  static const Color muted = Color(0xFF182126);
  static const Color mutedForeground = Color(0xFF93A4AD);
  static const Color accent = Color(0xFF223039);
  static const Color accentForeground = Color(0xFFF3F7F7);
  static const Color destructive = Color(0xFFF87171);
  static const Color destructiveForeground = Color(0xFF210B0F);
  static const Color border = Color(0xFF2A3841);
  static const Color input = Color(0xFF1D282E);
  static const Color ring = Color(0xFF4CC7BA);
  static const Color chart1 = Color(0xFF4CC7BA);
  static const Color chart2 = Color(0xFF60A5FA);
  static const Color chart3 = Color(0xFFFBBF24);
  static const Color chart4 = Color(0xFFA78BFA);
  static const Color chart5 = Color(0xFFF472B6);
  static const Color sidebar = Color(0xFF0F171B);
  static const Color sidebarForeground = Color(0xFFF3F7F7);
  static const Color sidebarPrimary = Color(0xFF4CC7BA);
  static const Color sidebarPrimaryForeground = Color(0xFF062321);
  static const Color sidebarAccent = Color(0xFF1E2A30);
  static const Color sidebarAccentForeground = Color(0xFFF3F7F7);
  static const Color sidebarBorder = Color(0xFF2A3841);
  static const Color sidebarRing = Color(0xFF4CC7BA);
  static const Color brandGold = Color(0xFFF1C27D);
  static const Color aiBubble = Color(0xFF1D272D);
  static const Color aiBubbleForeground = Color(0xFFF3F7F7);
  static const Color userBubble = Color(0xFF23344A);
  static const Color userBubbleForeground = Color(0xFFECF4FF);
  static const Color aiTool = Color(0xFF5A4524);
  static const Color aiToolForeground = Color(0xFFFEF3C7);
  static const Color success = Color(0xFF34D399);
  static const Color successForeground = Color(0xFF042118);

  /// Field names in declaration order (light/dark parity guard).
  static const List<String> tokenNames = ['background', 'foreground', 'card', 'cardForeground', 'popover', 'popoverForeground', 'primary', 'primaryForeground', 'secondary', 'secondaryForeground', 'muted', 'mutedForeground', 'accent', 'accentForeground', 'destructive', 'destructiveForeground', 'border', 'input', 'ring', 'chart1', 'chart2', 'chart3', 'chart4', 'chart5', 'sidebar', 'sidebarForeground', 'sidebarPrimary', 'sidebarPrimaryForeground', 'sidebarAccent', 'sidebarAccentForeground', 'sidebarBorder', 'sidebarRing', 'brandGold', 'aiBubble', 'aiBubbleForeground', 'userBubble', 'userBubbleForeground', 'aiTool', 'aiToolForeground', 'success', 'successForeground'];
}

class SlabMetrics {
  static const double radius = 15.2;
  static const double glassBlur = 14;
  static const Cubic easeOutExpo = Cubic(0.16, 1, 0.3, 1);
  static const double shellRail = 80;
  static const double shellTopbar = 56;
  static const double shellFooter = 32;
  static const double shellGutter = 24;
  static const List<String> fontSans = ['Outfit', 'Geist', 'Geist Fallback', 'system-ui', 'sans-serif'];
  static const List<String> fontMono = ['Fira Code', 'Geist Mono', 'Geist Mono Fallback', 'monospace'];
  static const double radiusXl = 19.2;
  static const double radius2xl = 24;
  static const double radius3xl = 32;
  static const double textMicro = 10;
  static const double textCaption = 11;
  static const double textLabel = 12;
  static const double textBody = 13;
  static const double trackingDisplay = -0.05;
  static const double trackingEyebrow = 0.16;
  static const double defaultTransitionDuration = 180;
  static const Cubic defaultTransitionTimingFunction = Cubic(0.16, 1, 0.3, 1);
  static const double radiusSm = 11.2;
  static const double radiusMd = 13.2;
  static const double radiusLg = 15.2;
}
