//! Request / response types for system telemetry APIs (`/v1/system/...`).

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use crate::domain::models::{
    GpuDeviceSnapshot, GpuStatusSnapshot, SystemDiagnosticPath, SystemDiagnosticsSnapshot,
};

/// Per-GPU snapshot from `all-smi`.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct GpuDeviceStatus {
    /// Stable GPU index in current snapshot.
    pub id: u32,
    /// Human-readable GPU model name.
    pub name: String,
    /// Device class from all-smi, e.g. GPU / NPU.
    pub device_type: String,
    /// Core utilization in percentage (0-100).
    pub utilization_percent: f64,
    /// Reported temperature in Celsius.
    pub temperature_celsius: u32,
    /// Current used VRAM bytes.
    pub used_memory_bytes: u64,
    /// Total VRAM bytes.
    pub total_memory_bytes: u64,
    /// Derived VRAM usage percentage (0-100).
    pub memory_usage_percent: f64,
    /// Current power draw in watts.
    pub power_draw_watts: f64,
}

/// Aggregated GPU monitor payload for the status bar.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct GpuStatusResponse {
    /// Whether GPU telemetry is available for this host.
    pub available: bool,
    /// Telemetry backend identifier.
    pub backend: String,
    /// RFC3339 timestamp generated by server.
    pub updated_at: String,
    /// Current GPU list snapshot.
    pub devices: Vec<GpuDeviceStatus>,
    /// Optional reason when telemetry is unavailable.
    pub error: Option<String>,
}

/// One local filesystem path included in the diagnostics snapshot.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct SystemDiagnosticPathResponse {
    pub label: String,
    pub path: String,
    pub exists: bool,
}

/// Read-only support snapshot for local desktop diagnostics.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct SystemDiagnosticsResponse {
    pub status: String,
    pub version: String,
    pub generated_at: String,
    pub transport_mode: String,
    pub swagger_enabled: bool,
    pub admin_token_configured: bool,
    pub cloud_http_trace_enabled: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cors_allowed_origins: Option<String>,
    pub paths: Vec<SystemDiagnosticPathResponse>,
}

impl From<GpuDeviceSnapshot> for GpuDeviceStatus {
    fn from(snapshot: GpuDeviceSnapshot) -> Self {
        Self {
            id: snapshot.id,
            name: snapshot.name,
            device_type: snapshot.device_type,
            utilization_percent: snapshot.utilization_percent,
            temperature_celsius: snapshot.temperature_celsius,
            used_memory_bytes: snapshot.used_memory_bytes,
            total_memory_bytes: snapshot.total_memory_bytes,
            memory_usage_percent: snapshot.memory_usage_percent,
            power_draw_watts: snapshot.power_draw_watts,
        }
    }
}

impl From<GpuStatusSnapshot> for GpuStatusResponse {
    fn from(snapshot: GpuStatusSnapshot) -> Self {
        Self {
            available: snapshot.available,
            backend: snapshot.backend,
            updated_at: snapshot.updated_at,
            devices: snapshot.devices.into_iter().map(Into::into).collect(),
            error: snapshot.error,
        }
    }
}

impl From<SystemDiagnosticPath> for SystemDiagnosticPathResponse {
    fn from(path: SystemDiagnosticPath) -> Self {
        Self { label: path.label, path: path.path, exists: path.exists }
    }
}

impl From<SystemDiagnosticsSnapshot> for SystemDiagnosticsResponse {
    fn from(snapshot: SystemDiagnosticsSnapshot) -> Self {
        Self {
            status: snapshot.status,
            version: snapshot.version,
            generated_at: snapshot.generated_at,
            transport_mode: snapshot.transport_mode,
            swagger_enabled: snapshot.swagger_enabled,
            admin_token_configured: snapshot.admin_token_configured,
            cloud_http_trace_enabled: snapshot.cloud_http_trace_enabled,
            cors_allowed_origins: snapshot.cors_allowed_origins,
            paths: snapshot.paths.into_iter().map(Into::into).collect(),
        }
    }
}
