//! Request / response types for system telemetry APIs (`/v1/system/...`).

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use crate::domain::models::{
    GpuDeviceSnapshot, GpuStatusSnapshot, SystemDiagnosticPath, SystemDiagnosticsSnapshot,
};

/// Per-GPU snapshot from `all-smi`.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct GpuDeviceStatus {
    /// Stable GPU index in current snapshot.
    pub id: u32,
    /// Human-readable GPU model name.
    pub name: String,
    /// Device class from all-smi, e.g. GPU / NPU.
    pub device_type: String,
    /// Core utilization in percentage (0-100).
    pub utilization_percent: f64,
    /// Reported temperature in Celsius.
    pub temperature_celsius: u32,
    /// Current used VRAM bytes.
    pub used_memory_bytes: u64,
    /// Total VRAM bytes.
    pub total_memory_bytes: u64,
    /// Derived VRAM usage percentage (0-100).
    pub memory_usage_percent: f64,
    /// Current power draw in watts.
    pub power_draw_watts: f64,
}

/// Aggregated GPU monitor payload for the status bar.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct GpuStatusResponse {
    /// Whether GPU telemetry is available for this host.
    pub available: bool,
    /// Telemetry backend identifier.
    pub backend: String,
    /// RFC3339 timestamp generated by server.
    pub updated_at: String,
    /// Current GPU list snapshot.
    pub devices: Vec<GpuDeviceStatus>,
    /// Optional reason when telemetry is unavailable.
    pub error: Option<String>,
}

/// One local filesystem path included in the diagnostics snapshot.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct SystemDiagnosticPathResponse {
    pub label: String,
    pub path: String,
    pub exists: bool,
}

/// Read-only support snapshot for local desktop diagnostics.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct SystemDiagnosticsResponse {
    pub status: String,
    pub version: String,
    pub generated_at: String,
    pub transport_mode: String,
    pub swagger_enabled: bool,
    pub admin_token_configured: bool,
    pub cloud_http_trace_enabled: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cors_allowed_origins: Option<String>,
    pub paths: Vec<SystemDiagnosticPathResponse>,
}

impl From<GpuDeviceSnapshot> for GpuDeviceStatus {
    fn from(snapshot: GpuDeviceSnapshot) -> Self {
        Self {
            id: snapshot.id,
            name: snapshot.name,
            device_type: snapshot.device_type,
            utilization_percent: snapshot.utilization_percent,
            temperature_celsius: snapshot.temperature_celsius,
            used_memory_bytes: snapshot.used_memory_bytes,
            total_memory_bytes: snapshot.total_memory_bytes,
            memory_usage_percent: snapshot.memory_usage_percent,
            power_draw_watts: snapshot.power_draw_watts,
        }
    }
}

impl From<GpuStatusSnapshot> for GpuStatusResponse {
    fn from(snapshot: GpuStatusSnapshot) -> Self {
        Self {
            available: snapshot.available,
            backend: snapshot.backend,
            updated_at: snapshot.updated_at,
            devices: snapshot.devices.into_iter().map(Into::into).collect(),
            error: snapshot.error,
        }
    }
}

impl From<SystemDiagnosticPath> for SystemDiagnosticPathResponse {
    fn from(path: SystemDiagnosticPath) -> Self {
        Self { label: path.label, path: path.path, exists: path.exists }
    }
}

impl From<SystemDiagnosticsSnapshot> for SystemDiagnosticsResponse {
    fn from(snapshot: SystemDiagnosticsSnapshot) -> Self {
        Self {
            status: snapshot.status,
            version: snapshot.version,
            generated_at: snapshot.generated_at,
            transport_mode: snapshot.transport_mode,
            swagger_enabled: snapshot.swagger_enabled,
            admin_token_configured: snapshot.admin_token_configured,
            cloud_http_trace_enabled: snapshot.cloud_http_trace_enabled,
            cors_allowed_origins: snapshot.cors_allowed_origins,
            paths: snapshot.paths.into_iter().map(Into::into).collect(),
        }
    }
}

/// One agent thread summary in the diagnostics snapshot (INFRA-08). No message
/// content, config, or secret data is representable — the source whitelist type
/// (`slab_utils::diagnostics::ThreadStat`) forbids them by construction.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct AgentThreadStatResponse {
    pub thread_id: String,
    pub status: String,
    pub turn_index: u32,
    pub depth: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

/// One failed tool call in the diagnostics snapshot (tool name + error only).
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct FailedToolCallResponse {
    pub tool_name: String,
    pub error: String,
}

/// Aggregated agent diagnostics: recent thread stats + recent failed tool calls.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct AgentDiagnosticsResponse {
    pub threads: Vec<AgentThreadStatResponse>,
    pub failed_tool_calls: Vec<FailedToolCallResponse>,
}

impl From<slab_utils::diagnostics::ThreadStat> for AgentThreadStatResponse {
    fn from(stat: slab_utils::diagnostics::ThreadStat) -> Self {
        Self {
            thread_id: stat.thread_id,
            status: stat.status,
            turn_index: stat.turn_index,
            depth: stat.depth,
            reason: stat.reason,
        }
    }
}

impl From<slab_utils::diagnostics::FailedToolCall> for FailedToolCallResponse {
    fn from(call: slab_utils::diagnostics::FailedToolCall) -> Self {
        Self { tool_name: call.tool_name, error: call.error }
    }
}

/// One resident model's ledger entry (diagnostics). The ledger is
/// attribution — probe-measured free bytes remain the decision input.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct GpuLedgerEntryResponse {
    /// Backend canonical id, e.g. "ggml.llama".
    pub backend: String,
    /// Model id when the load was dispatched for a catalog model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    /// Model weights file path as loaded.
    pub model_path: String,
    pub num_workers: usize,
    /// Engine-resolved `n_ctx` (what `auto` sized to), when reported.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolved_context_length: Option<u32>,
    /// Whether a multimodal projector is resident alongside the model.
    pub mmproj_resident: bool,
    /// Weights file size in bytes (best-effort stat).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub weights_bytes: Option<u64>,
    /// Projector file size in bytes (best-effort stat).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mmproj_bytes: Option<u64>,
    /// Measured free-VRAM delta across the load (probe before vs after).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub measured_delta_bytes: Option<u64>,
    /// RFC3339 timestamp of the recorded load.
    pub recorded_at: String,
}

/// Probe gauge folded into a ledger row. `free = total − used` (all-smi
/// reports no free; the scheduler derives it).
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct GpuLedgerGaugeResponse {
    pub used_bytes: u64,
    pub total_bytes: u64,
    pub free_bytes: u64,
}

/// Per-device ledger: last-synced gauge + resident model entries.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct GpuLedgerDeviceResponse {
    pub uuid: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gauge: Option<GpuLedgerGaugeResponse>,
    pub resident: Vec<GpuLedgerEntryResponse>,
}

/// Resident-model memory ledger exposed at `/v1/system/gpu/ledger`
/// (diagnostics-only; the `/v1/system/gpu` response shape stays frozen).
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct GpuLedgerResponse {
    pub devices: Vec<GpuLedgerDeviceResponse>,
}

impl From<slab_gpu_memory_scheduler::LedgerEntry> for GpuLedgerEntryResponse {
    fn from(entry: slab_gpu_memory_scheduler::LedgerEntry) -> Self {
        Self {
            backend: entry.backend.to_string(),
            model_id: entry.model_id,
            model_path: entry.model_path,
            num_workers: entry.num_workers,
            resolved_context_length: entry.resolved_context_length,
            mmproj_resident: entry.mmproj_resident,
            weights_bytes: entry.weights_bytes,
            mmproj_bytes: entry.mmproj_bytes,
            measured_delta_bytes: entry.measured_delta_bytes,
            recorded_at: entry.recorded_at.to_rfc3339(),
        }
    }
}

impl From<slab_gpu_memory_scheduler::DeviceMemoryGauge> for GpuLedgerGaugeResponse {
    fn from(gauge: slab_gpu_memory_scheduler::DeviceMemoryGauge) -> Self {
        Self {
            used_bytes: gauge.used_bytes,
            total_bytes: gauge.total_bytes,
            free_bytes: gauge.free_bytes(),
        }
    }
}

impl From<slab_gpu_memory_scheduler::DeviceLedger> for GpuLedgerDeviceResponse {
    fn from(device: slab_gpu_memory_scheduler::DeviceLedger) -> Self {
        Self {
            uuid: device.uuid,
            gauge: device.gauge.map(Into::into),
            resident: device.resident.into_iter().map(Into::into).collect(),
        }
    }
}
