from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.gpu_device_status import GpuDeviceStatus


T = TypeVar("T", bound="GpuStatusResponse")


@_attrs_define
class GpuStatusResponse:
    """Aggregated GPU monitor payload for the status bar.

    Attributes:
        available (bool): Whether GPU telemetry is available for this host.
        backend (str): Telemetry backend identifier.
        devices (list[GpuDeviceStatus]): Current GPU list snapshot.
        updated_at (str): RFC3339 timestamp generated by server.
        error (None | str | Unset): Optional reason when telemetry is unavailable.
    """

    available: bool
    backend: str
    devices: list[GpuDeviceStatus]
    updated_at: str
    error: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        available = self.available

        backend = self.backend

        devices = []
        for devices_item_data in self.devices:
            devices_item = devices_item_data.to_dict()
            devices.append(devices_item)

        updated_at = self.updated_at

        error: None | str | Unset
        if isinstance(self.error, Unset):
            error = UNSET
        else:
            error = self.error

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "available": available,
                "backend": backend,
                "devices": devices,
                "updated_at": updated_at,
            }
        )
        if error is not UNSET:
            field_dict["error"] = error

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.gpu_device_status import GpuDeviceStatus

        d = dict(src_dict)
        available = d.pop("available")

        backend = d.pop("backend")

        devices = []
        _devices = d.pop("devices")
        for devices_item_data in _devices:
            devices_item = GpuDeviceStatus.from_dict(devices_item_data)

            devices.append(devices_item)

        updated_at = d.pop("updated_at")

        def _parse_error(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        error = _parse_error(d.pop("error", UNSET))

        gpu_status_response = cls(
            available=available,
            backend=backend,
            devices=devices,
            updated_at=updated_at,
            error=error,
        )

        gpu_status_response.additional_properties = d
        return gpu_status_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
