[env]
AWS_LC_SYS_PREBUILT_NASM = { value = "1", force = false }
FFMPEG_DIR = { value = "C:/Users/cyberhan/Desktop/0411/slab/slab.rs/.slab/ffmpeg-sdk/windows-x64/ffmpeg-n7.1-latest-win64-gpl-shared-7.1", force = false }