/**
 * Main API entry point
 *
 * Re-exports all API functionality
 */

import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./v1.d.ts"; // generated by openapi-typescript
import { errorMiddleware } from "./errors";
import { tauriAwareFetch } from "./tauri-transport";

import { QueryClient } from '@tanstack/react-query'

// Get API configuration from environment
import { SERVER_BASE_URL } from '../config';

const fetchClient = createFetchClient<paths>({
  baseUrl: `${SERVER_BASE_URL}/`,
  fetch: tauriAwareFetch,
});

// Register error middleware
fetchClient.use(errorMiddleware);

const api = createClient(fetchClient);


const queryClient = new QueryClient({})


// Export default API client
export default api;

// Export types
export type { paths } from './v1.d.ts';

// Export error handling
export {
  ApiError,
  errorMiddleware,
  getErrorMessage,
  getErrorCode,
  isApiError,
} from './errors';
export { queryClient };
export type { ApiErrorResponse } from './errors';
