use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomToolCall {
    /// The type of the custom tool call. Always `custom_tool_call`.
    #[serde(rename = "type")]
    pub r#type: CustomToolCallType,
    /// An identifier used to map this custom tool call to a tool call output.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The name of the custom tool being called.
    #[serde(rename = "name")]
    pub name: String,
    /// The input for the custom tool call generated by the model.
    #[serde(rename = "input")]
    pub input: String,
    /// The unique ID of the custom tool call in the OpenAI platform.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The namespace of the custom tool being called.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

impl CustomToolCall {
    /// A call to a custom tool created by the model.
    pub fn new(
        r#type: CustomToolCallType,
        call_id: String,
        name: String,
        input: String,
    ) -> CustomToolCall {
        CustomToolCall { r#type, call_id, name, input, id: None, namespace: None }
    }
}
/// The type of the custom tool call. Always `custom_tool_call`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CustomToolCallType {
    #[serde(rename = "custom_tool_call")]
    #[default]
    CustomToolCall,
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomToolCallOutput {
    /// The type of the custom tool call output. Always `custom_tool_call_output`.
    #[serde(rename = "type")]
    pub r#type: CustomToolCallOutputType,
    /// The call ID, used to map this custom tool call output to a custom tool call.
    #[serde(rename = "call_id")]
    pub call_id: String,
    #[serde(rename = "output")]
    pub output: Box<models::CustomToolCallOutputOutput>,
    /// The unique ID of the custom tool call output in the OpenAI platform.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl CustomToolCallOutput {
    /// The output of a custom tool call from your code, being sent back to the model.
    pub fn new(
        r#type: CustomToolCallOutputType,
        call_id: String,
        output: models::CustomToolCallOutputOutput,
    ) -> CustomToolCallOutput {
        CustomToolCallOutput { r#type, call_id, output: Box::new(output), id: None }
    }
}
/// The type of the custom tool call output. Always `custom_tool_call_output`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CustomToolCallOutputType {
    #[serde(rename = "custom_tool_call_output")]
    #[default]
    CustomToolCallOutput,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustomToolCallOutputOutput {
    /// A string of the output of the custom tool call.
    StringOutput(String),
    /// Text, image, or file output of the custom tool call.
    OutputContentList(Vec<models::FunctionAndCustomToolCallOutput>),
}

impl Default for CustomToolCallOutputOutput {
    fn default() -> Self {
        Self::StringOutput(Default::default())
    }
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomToolCallOutputResource {
    /// The type of the custom tool call output. Always `custom_tool_call_output`.
    #[serde(rename = "type")]
    pub r#type: CustomToolCallOutputResourceType,
    /// The unique ID of the custom tool call output item.
    #[serde(rename = "id")]
    pub id: String,
    /// The call ID, used to map this custom tool call output to a custom tool call.
    #[serde(rename = "call_id")]
    pub call_id: String,
    #[serde(rename = "output")]
    pub output: Box<models::CustomToolCallOutputOutput>,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    #[serde(rename = "status")]
    pub status: models::FunctionCallOutputStatusEnum,
    /// The identifier of the actor that created the item.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl CustomToolCallOutputResource {
    pub fn new(
        r#type: CustomToolCallOutputResourceType,
        id: String,
        call_id: String,
        output: models::CustomToolCallOutputOutput,
        status: models::FunctionCallOutputStatusEnum,
    ) -> CustomToolCallOutputResource {
        CustomToolCallOutputResource {
            r#type,
            id,
            call_id,
            output: Box::new(output),
            status,
            created_by: None,
        }
    }
}
/// The type of the custom tool call output. Always `custom_tool_call_output`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CustomToolCallOutputResourceType {
    #[serde(rename = "custom_tool_call_output")]
    #[default]
    CustomToolCallOutput,
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomToolCallResource {
    /// The type of the custom tool call. Always `custom_tool_call`.
    #[serde(rename = "type")]
    pub r#type: CustomToolCallResourceType,
    /// The unique ID of the custom tool call item.
    #[serde(rename = "id")]
    pub id: String,
    /// An identifier used to map this custom tool call to a tool call output.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The name of the custom tool being called.
    #[serde(rename = "name")]
    pub name: String,
    /// The input for the custom tool call generated by the model.
    #[serde(rename = "input")]
    pub input: String,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    #[serde(rename = "status")]
    pub status: models::FunctionCallStatus,
    /// The namespace of the custom tool being called.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// The identifier of the actor that created the item.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl CustomToolCallResource {
    pub fn new(
        r#type: CustomToolCallResourceType,
        id: String,
        call_id: String,
        name: String,
        input: String,
        status: models::FunctionCallStatus,
    ) -> CustomToolCallResource {
        CustomToolCallResource {
            r#type,
            id,
            call_id,
            name,
            input,
            status,
            namespace: None,
            created_by: None,
        }
    }
}
/// The type of the custom tool call. Always `custom_tool_call`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CustomToolCallResourceType {
    #[serde(rename = "custom_tool_call")]
    #[default]
    CustomToolCall,
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomToolChatCompletions {
    /// The type of the custom tool. Always `custom`.
    #[serde(rename = "type")]
    pub r#type: CustomToolChatCompletionsType,
    #[serde(rename = "custom")]
    pub custom: Box<models::CustomToolProperties>,
}

impl CustomToolChatCompletions {
    /// A custom tool that processes input using a specified format.
    pub fn new(
        r#type: CustomToolChatCompletionsType,
        custom: models::CustomToolProperties,
    ) -> CustomToolChatCompletions {
        CustomToolChatCompletions { r#type, custom: Box::new(custom) }
    }
}
/// The type of the custom tool. Always `custom`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CustomToolChatCompletionsType {
    #[serde(rename = "custom")]
    #[default]
    Custom,
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomToolParam {
    /// The type of the custom tool. Always `custom`.
    #[serde(rename = "type")]
    pub r#type: CustomToolParamType,
    /// The name of the custom tool, used to identify it in tool calls.
    #[serde(rename = "name")]
    pub name: String,
    /// Optional description of the custom tool, used to provide more context.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<Box<models::CustomToolParamFormat>>,
    /// Whether this tool should be deferred and discovered via tool search.
    #[serde(rename = "defer_loading", skip_serializing_if = "Option::is_none")]
    pub defer_loading: Option<bool>,
}

impl CustomToolParam {
    /// A custom tool that processes input using a specified format. Learn more about   [custom tools](/docs/guides/function-calling#custom-tools)
    pub fn new(r#type: CustomToolParamType, name: String) -> CustomToolParam {
        CustomToolParam { r#type, name, description: None, format: None, defer_loading: None }
    }
}
/// The type of the custom tool. Always `custom`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CustomToolParamType {
    #[serde(rename = "custom")]
    #[default]
    Custom,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CustomToolParamFormat {
    #[serde(rename = "CustomTextFormatParam")]
    CustomTextFormatParam(Box<models::CustomTextFormatParam>),
    #[serde(rename = "CustomGrammarFormatParam")]
    CustomGrammarFormatParam(Box<models::CustomGrammarFormatParam>),
}

impl Default for CustomToolParamFormat {
    fn default() -> Self {
        Self::CustomTextFormatParam(Default::default())
    }
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomToolProperties {
    /// The name of the custom tool, used to identify it in tool calls.
    #[serde(rename = "name")]
    pub name: String,
    /// Optional description of the custom tool, used to provide more context.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<Box<models::CustomToolPropertiesFormat>>,
}

impl CustomToolProperties {
    /// Properties of the custom tool.
    pub fn new(name: String) -> CustomToolProperties {
        CustomToolProperties { name, description: None, format: None }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustomToolPropertiesFormat {
    TextFormat(Box<models::TextFormat>),
    GrammarFormat(Box<models::GrammarFormat>),
}

impl Default for CustomToolPropertiesFormat {
    fn default() -> Self {
        Self::TextFormat(Default::default())
    }
}
