use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionTool {
    /// The type of the function tool. Always `function`.
    #[serde(rename = "type")]
    pub r#type: FunctionToolType,
    /// The name of the function to call.
    #[serde(rename = "name")]
    pub name: String,
    /// A JSON schema object describing the parameters of the function.
    #[serde(rename = "parameters", deserialize_with = "Option::deserialize")]
    pub parameters: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Whether to enforce strict parameter validation. Default `true`.
    #[serde(rename = "strict", deserialize_with = "Option::deserialize")]
    pub strict: Option<bool>,
    /// A description of the function. Used by the model to determine whether or not to call the function.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// Whether this function is deferred and loaded via tool search.
    #[serde(rename = "defer_loading", skip_serializing_if = "Option::is_none")]
    pub defer_loading: Option<bool>,
}

impl FunctionTool {
    /// Defines a function in your own code the model can choose to call. Learn more about [function calling](https://platform.openai.com/docs/guides/function-calling).
    pub fn new(
        r#type: FunctionToolType,
        name: String,
        parameters: Option<std::collections::HashMap<String, serde_json::Value>>,
        strict: Option<bool>,
    ) -> FunctionTool {
        FunctionTool { r#type, name, parameters, strict, description: None, defer_loading: None }
    }
}
/// The type of the function tool. Always `function`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionToolType {
    #[serde(rename = "function")]
    #[default]
    Function,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionToolCall {
    /// The type of the function tool call. Always `function_call`.
    #[serde(rename = "type")]
    pub r#type: FunctionToolCallType,
    /// The unique ID of the function tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The name of the function to run.
    #[serde(rename = "name")]
    pub name: String,
    /// A JSON string of the arguments to pass to the function.
    #[serde(rename = "arguments")]
    pub arguments: String,
    /// The unique ID of the function tool call.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The namespace of the function to run.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<FunctionToolCallStatus>,
}

impl FunctionToolCall {
    /// A tool call to run a function. See the  [function calling guide](/docs/guides/function-calling) for more information.
    pub fn new(
        r#type: FunctionToolCallType,
        call_id: String,
        name: String,
        arguments: String,
    ) -> FunctionToolCall {
        FunctionToolCall {
            r#type,
            call_id,
            name,
            arguments,
            id: None,
            namespace: None,
            status: None,
        }
    }
}
/// The type of the function tool call. Always `function_call`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionToolCallType {
    #[serde(rename = "function_call")]
    #[default]
    FunctionCall,
}

/// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionToolCallStatus {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionToolCallOutput {
    /// The type of the function tool call output. Always `function_call_output`.
    #[serde(rename = "type")]
    pub r#type: FunctionToolCallOutputType,
    /// The unique ID of the function tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    #[serde(rename = "output")]
    pub output: Box<models::FunctionToolCallOutputOutput>,
    /// The unique ID of the function tool call output. Populated when this item is returned via API.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<FunctionToolCallOutputStatus>,
}

impl FunctionToolCallOutput {
    /// The output of a function tool call.
    pub fn new(
        r#type: FunctionToolCallOutputType,
        call_id: String,
        output: models::FunctionToolCallOutputOutput,
    ) -> FunctionToolCallOutput {
        FunctionToolCallOutput { r#type, call_id, output: Box::new(output), id: None, status: None }
    }
}
/// The type of the function tool call output. Always `function_call_output`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionToolCallOutputType {
    #[serde(rename = "function_call_output")]
    #[default]
    FunctionCallOutput,
}

/// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionToolCallOutputStatus {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}


#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FunctionToolCallOutputOutput {
    /// A string of the output of the function call.
    StringOutput(String),
    /// Text, image, or file output of the function call.
    OutputContentList(Vec<models::FunctionAndCustomToolCallOutput>),
}

impl Default for FunctionToolCallOutputOutput {
    fn default() -> Self {
        Self::StringOutput(Default::default())
    }
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionToolCallOutputResource {
    /// The unique ID of the function call tool output.
    #[serde(rename = "id")]
    pub id: String,
    /// The type of the function tool call output. Always `function_call_output`.
    #[serde(rename = "type")]
    pub r#type: FunctionToolCallOutputResourceType,
    /// The unique ID of the function tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    #[serde(rename = "output")]
    pub output: Box<models::FunctionToolCallOutputOutput>,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    #[serde(rename = "status")]
    pub status: models::FunctionCallOutputStatusEnum,
    /// The identifier of the actor that created the item.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl FunctionToolCallOutputResource {
    pub fn new(
        id: String,
        r#type: FunctionToolCallOutputResourceType,
        call_id: String,
        output: models::FunctionToolCallOutputOutput,
        status: models::FunctionCallOutputStatusEnum,
    ) -> FunctionToolCallOutputResource {
        FunctionToolCallOutputResource {
            id,
            r#type,
            call_id,
            output: Box::new(output),
            status,
            created_by: None,
        }
    }
}
/// The type of the function tool call output. Always `function_call_output`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionToolCallOutputResourceType {
    #[serde(rename = "function_call_output")]
    #[default]
    FunctionCallOutput,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionToolCallResource {
    /// The unique ID of the function tool call.
    #[serde(rename = "id")]
    pub id: String,
    /// The type of the function tool call. Always `function_call`.
    #[serde(rename = "type")]
    pub r#type: FunctionToolCallResourceType,
    /// The unique ID of the function tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The name of the function to run.
    #[serde(rename = "name")]
    pub name: String,
    /// A JSON string of the arguments to pass to the function.
    #[serde(rename = "arguments")]
    pub arguments: String,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    #[serde(rename = "status")]
    pub status: models::FunctionCallStatus,
    /// The namespace of the function to run.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// The identifier of the actor that created the item.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl FunctionToolCallResource {
    pub fn new(
        id: String,
        r#type: FunctionToolCallResourceType,
        call_id: String,
        name: String,
        arguments: String,
        status: models::FunctionCallStatus,
    ) -> FunctionToolCallResource {
        FunctionToolCallResource {
            id,
            r#type,
            call_id,
            name,
            arguments,
            status,
            namespace: None,
            created_by: None,
        }
    }
}
/// The type of the function tool call. Always `function_call`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionToolCallResourceType {
    #[serde(rename = "function_call")]
    #[default]
    FunctionCall,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionToolParam {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: FunctionToolParamType,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(
        rename = "parameters",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parameters: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "strict",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub strict: Option<Option<bool>>,
    /// Whether this function should be deferred and discovered via tool search.
    #[serde(rename = "defer_loading", skip_serializing_if = "Option::is_none")]
    pub defer_loading: Option<bool>,
}

impl FunctionToolParam {
    pub fn new(name: String, r#type: FunctionToolParamType) -> FunctionToolParam {
        FunctionToolParam {
            name,
            r#type,
            description: None,
            parameters: None,
            strict: None,
            defer_loading: None,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionToolParamType {
    #[serde(rename = "function")]
    #[default]
    Function,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionObject {
    /// The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
    #[serde(rename = "name")]
    pub name: String,
    /// A description of what the function does, used by the model to choose when and how to call the function.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The parameters the functions accepts, described as a JSON Schema object. See the [guide](/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format.   Omitting `parameters` defines a function with an empty parameter list.
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Whether to enable strict schema adherence when generating the function call. If set to true, the model will follow the exact schema defined in the `parameters` field. Only a subset of JSON Schema is supported when `strict` is `true`. Learn more about Structured Outputs in the [function calling guide](/docs/guides/function-calling).
    #[serde(
        rename = "strict",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub strict: Option<Option<bool>>,
}

impl FunctionObject {
    pub fn new(name: String) -> FunctionObject {
        FunctionObject { name, description: None, parameters: None, strict: None }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionCallItemStatus {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}

impl std::fmt::Display for FunctionCallItemStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InProgress => write!(f, "in_progress"),
            Self::Completed => write!(f, "completed"),
            Self::Incomplete => write!(f, "incomplete"),
        }
    }
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionCallOutputItemParam {
    /// The unique ID of the function tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The type of the function tool call output. Always `function_call_output`.
    #[serde(rename = "type")]
    pub r#type: FunctionCallOutputItemParamType,
    #[serde(rename = "output")]
    pub output: Box<models::FunctionCallOutputItemParamOutput>,
    /// The unique ID of the function tool call output. Populated when this item is returned via API.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    #[serde(
        rename = "status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<Option<models::FunctionCallItemStatus>>,
}

impl FunctionCallOutputItemParam {
    /// The output of a function tool call.
    pub fn new(
        call_id: String,
        r#type: FunctionCallOutputItemParamType,
        output: models::FunctionCallOutputItemParamOutput,
    ) -> FunctionCallOutputItemParam {
        FunctionCallOutputItemParam {
            call_id,
            r#type,
            output: Box::new(output),
            id: None,
            status: None,
        }
    }
}
/// The type of the function tool call output. Always `function_call_output`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionCallOutputItemParamType {
    #[serde(rename = "function_call_output")]
    #[default]
    FunctionCallOutput,
}


#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FunctionCallOutputItemParamOutput {
    /// A JSON string of the output of the function tool call.
    String(String),
    /// An array of content outputs (text, image, file) for the function tool call.
    ArrayVecFunctionCallOutputItemParamOutputOneOfInner(
        Vec<models::FunctionCallOutputItemParamOutputOneOfInner>,
    ),
}

impl Default for FunctionCallOutputItemParamOutput {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FunctionCallOutputItemParamOutputOneOfInner {
    #[serde(rename = "InputTextContentParam")]
    InputTextContentParam(Box<models::InputTextContentParam>),
    #[serde(rename = "InputImageContentParamAutoParam")]
    InputImageContentParamAutoParam(Box<models::InputImageContentParamAutoParam>),
    #[serde(rename = "InputFileContentParam")]
    InputFileContentParam(Box<models::InputFileContentParam>),
}

impl Default for FunctionCallOutputItemParamOutputOneOfInner {
    fn default() -> Self {
        Self::InputTextContentParam(Default::default())
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionCallOutputStatusEnum {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}

impl std::fmt::Display for FunctionCallOutputStatusEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InProgress => write!(f, "in_progress"),
            Self::Completed => write!(f, "completed"),
            Self::Incomplete => write!(f, "incomplete"),
        }
    }
}


#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionCallStatus {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}

impl std::fmt::Display for FunctionCallStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InProgress => write!(f, "in_progress"),
            Self::Completed => write!(f, "completed"),
            Self::Incomplete => write!(f, "incomplete"),
        }
    }
}


#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FunctionAndCustomToolCallOutput {
    #[serde(rename = "InputTextContent")]
    InputTextContent(Box<models::InputTextContent>),
    #[serde(rename = "InputImageContent")]
    InputImageContent(Box<models::InputImageContent>),
    #[serde(rename = "InputFileContent")]
    InputFileContent(Box<models::InputFileContent>),
}

impl Default for FunctionAndCustomToolCallOutput {
    fn default() -> Self {
        Self::InputTextContent(Default::default())
    }
}
