use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellAction {
    #[serde(rename = "commands")]
    pub commands: Vec<String>,
    /// Optional timeout in milliseconds for the commands.
    #[serde(rename = "timeout_ms", deserialize_with = "Option::deserialize")]
    pub timeout_ms: Option<i32>,
    /// Optional maximum number of characters to return from each command.
    #[serde(rename = "max_output_length", deserialize_with = "Option::deserialize")]
    pub max_output_length: Option<i32>,
}

impl FunctionShellAction {
    /// Execute a shell command.
    pub fn new(
        commands: Vec<String>,
        timeout_ms: Option<i32>,
        max_output_length: Option<i32>,
    ) -> FunctionShellAction {
        FunctionShellAction { commands, timeout_ms, max_output_length }
    }
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellActionParam {
    /// Ordered shell commands for the execution environment to run.
    #[serde(rename = "commands")]
    pub commands: Vec<String>,
    /// Maximum wall-clock time in milliseconds to allow the shell commands to run.
    #[serde(
        rename = "timeout_ms",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub timeout_ms: Option<Option<i32>>,
    /// Maximum number of UTF-8 characters to capture from combined stdout and stderr output.
    #[serde(
        rename = "max_output_length",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_output_length: Option<Option<i32>>,
}

impl FunctionShellActionParam {
    /// Commands and limits describing how to run the shell tool call.
    pub fn new(commands: Vec<String>) -> FunctionShellActionParam {
        FunctionShellActionParam { commands, timeout_ms: None, max_output_length: None }
    }
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellCall {
    /// The type of the item. Always `shell_call`.
    #[serde(rename = "type")]
    pub r#type: FunctionShellCallType,
    /// The unique ID of the shell tool call. Populated when this item is returned via API.
    #[serde(rename = "id")]
    pub id: String,
    /// The unique ID of the shell tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The shell commands and limits that describe how to run the tool call.
    #[serde(rename = "action")]
    pub action: Box<models::FunctionShellAction>,
    /// The status of the shell call. One of `in_progress`, `completed`, or `incomplete`.
    #[serde(rename = "status")]
    pub status: models::FunctionShellCallStatus,
    #[serde(rename = "environment", deserialize_with = "Option::deserialize")]
    pub environment: Option<Box<models::FunctionShellCallEnvironment>>,
    /// The ID of the entity that created this tool call.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl FunctionShellCall {
    /// A tool call that executes one or more shell commands in a managed environment.
    pub fn new(
        r#type: FunctionShellCallType,
        id: String,
        call_id: String,
        action: models::FunctionShellAction,
        status: models::FunctionShellCallStatus,
        environment: Option<models::FunctionShellCallEnvironment>,
    ) -> FunctionShellCall {
        FunctionShellCall {
            r#type,
            id,
            call_id,
            action: Box::new(action),
            status,
            environment: environment.map(Box::new),
            created_by: None,
        }
    }
}
/// The type of the item. Always `shell_call`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum FunctionShellCallType {
    #[serde(rename = "shell_call")]
    #[default]
    ShellCall,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellCallItemParam {
    /// The unique ID of the shell tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The type of the item. Always `shell_call`.
    #[serde(rename = "type")]
    pub r#type: FunctionShellCallItemParamType,
    /// The shell commands and limits that describe how to run the tool call.
    #[serde(rename = "action")]
    pub action: Box<models::FunctionShellActionParam>,
    /// The unique ID of the shell tool call. Populated when this item is returned via API.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    /// The status of the shell call. One of `in_progress`, `completed`, or `incomplete`.
    #[serde(
        rename = "status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<Option<models::FunctionShellCallItemStatus>>,
    #[serde(
        rename = "environment",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub environment: Option<Option<Box<models::FunctionShellCallItemParamEnvironment>>>,
}

impl FunctionShellCallItemParam {
    /// A tool representing a request to execute one or more shell commands.
    pub fn new(
        call_id: String,
        r#type: FunctionShellCallItemParamType,
        action: models::FunctionShellActionParam,
    ) -> FunctionShellCallItemParam {
        FunctionShellCallItemParam {
            call_id,
            r#type,
            action: Box::new(action),
            id: None,
            status: None,
            environment: None,
        }
    }
}
/// The type of the item. Always `shell_call`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum FunctionShellCallItemParamType {
    #[serde(rename = "shell_call")]
    #[default]
    ShellCall,
}


#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionShellCallItemStatus {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}

impl std::fmt::Display for FunctionShellCallItemStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InProgress => write!(f, "in_progress"),
            Self::Completed => write!(f, "completed"),
            Self::Incomplete => write!(f, "incomplete"),
        }
    }
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellCallOutput {
    /// The type of the shell call output. Always `shell_call_output`.
    #[serde(rename = "type")]
    pub r#type: FunctionShellCallOutputType,
    /// The unique ID of the shell call output. Populated when this item is returned via API.
    #[serde(rename = "id")]
    pub id: String,
    /// The unique ID of the shell tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The status of the shell call output. One of `in_progress`, `completed`, or `incomplete`.
    #[serde(rename = "status")]
    pub status: models::FunctionShellCallOutputStatusEnum,
    /// An array of shell call output contents
    #[serde(rename = "output")]
    pub output: Vec<models::FunctionShellCallOutputContent>,
    /// The maximum length of the shell command output. This is generated by the model and should be passed back with the raw output.
    #[serde(rename = "max_output_length", deserialize_with = "Option::deserialize")]
    pub max_output_length: Option<i32>,
    /// The identifier of the actor that created the item.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl FunctionShellCallOutput {
    /// The output of a shell tool call that was emitted.
    pub fn new(
        r#type: FunctionShellCallOutputType,
        id: String,
        call_id: String,
        status: models::FunctionShellCallOutputStatusEnum,
        output: Vec<models::FunctionShellCallOutputContent>,
        max_output_length: Option<i32>,
    ) -> FunctionShellCallOutput {
        FunctionShellCallOutput {
            r#type,
            id,
            call_id,
            status,
            output,
            max_output_length,
            created_by: None,
        }
    }
}
/// The type of the shell call output. Always `shell_call_output`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum FunctionShellCallOutputType {
    #[serde(rename = "shell_call_output")]
    #[default]
    ShellCallOutput,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellCallOutputContent {
    /// The standard output that was captured.
    #[serde(rename = "stdout")]
    pub stdout: String,
    /// The standard error output that was captured.
    #[serde(rename = "stderr")]
    pub stderr: String,
    #[serde(rename = "outcome")]
    pub outcome: Box<models::ShellCallOutcome>,
    /// The identifier of the actor that created the item.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl FunctionShellCallOutputContent {
    /// The content of a shell tool call output that was emitted.
    pub fn new(
        stdout: String,
        stderr: String,
        outcome: models::ShellCallOutcome,
    ) -> FunctionShellCallOutputContent {
        FunctionShellCallOutputContent {
            stdout,
            stderr,
            outcome: Box::new(outcome),
            created_by: None,
        }
    }
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellCallOutputContentParam {
    /// Captured stdout output for the shell call.
    #[serde(rename = "stdout")]
    pub stdout: String,
    /// Captured stderr output for the shell call.
    #[serde(rename = "stderr")]
    pub stderr: String,
    /// The exit or timeout outcome associated with this shell call.
    #[serde(rename = "outcome")]
    pub outcome: Box<models::FunctionShellCallOutputOutcomeParam>,
}

impl FunctionShellCallOutputContentParam {
    /// Captured stdout and stderr for a portion of a shell tool call output.
    pub fn new(
        stdout: String,
        stderr: String,
        outcome: models::FunctionShellCallOutputOutcomeParam,
    ) -> FunctionShellCallOutputContentParam {
        FunctionShellCallOutputContentParam { stdout, stderr, outcome: Box::new(outcome) }
    }
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellCallOutputExitOutcome {
    /// The outcome type. Always `exit`.
    #[serde(rename = "type")]
    pub r#type: FunctionShellCallOutputExitOutcomeType,
    /// Exit code from the shell process.
    #[serde(rename = "exit_code")]
    pub exit_code: i32,
}

impl FunctionShellCallOutputExitOutcome {
    /// Indicates that the shell commands finished and returned an exit code.
    pub fn new(
        r#type: FunctionShellCallOutputExitOutcomeType,
        exit_code: i32,
    ) -> FunctionShellCallOutputExitOutcome {
        FunctionShellCallOutputExitOutcome { r#type, exit_code }
    }
}
/// The outcome type. Always `exit`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum FunctionShellCallOutputExitOutcomeType {
    #[serde(rename = "exit")]
    #[default]
    Exit,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellCallOutputExitOutcomeParam {
    /// The outcome type. Always `exit`.
    #[serde(rename = "type")]
    pub r#type: FunctionShellCallOutputExitOutcomeParamType,
    /// The exit code returned by the shell process.
    #[serde(rename = "exit_code")]
    pub exit_code: i32,
}

impl FunctionShellCallOutputExitOutcomeParam {
    /// Indicates that the shell commands finished and returned an exit code.
    pub fn new(
        r#type: FunctionShellCallOutputExitOutcomeParamType,
        exit_code: i32,
    ) -> FunctionShellCallOutputExitOutcomeParam {
        FunctionShellCallOutputExitOutcomeParam { r#type, exit_code }
    }
}
/// The outcome type. Always `exit`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum FunctionShellCallOutputExitOutcomeParamType {
    #[serde(rename = "exit")]
    #[default]
    Exit,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellCallOutputItemParam {
    /// The unique ID of the shell tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    /// The type of the item. Always `shell_call_output`.
    #[serde(rename = "type")]
    pub r#type: FunctionShellCallOutputItemParamType,
    /// Captured chunks of stdout and stderr output, along with their associated outcomes.
    #[serde(rename = "output")]
    pub output: Vec<models::FunctionShellCallOutputContentParam>,
    /// The unique ID of the shell tool call output. Populated when this item is returned via API.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    /// The status of the shell call output.
    #[serde(
        rename = "status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<Option<models::FunctionShellCallItemStatus>>,
    /// The maximum number of UTF-8 characters captured for this shell call's combined output.
    #[serde(
        rename = "max_output_length",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_output_length: Option<Option<i32>>,
}

impl FunctionShellCallOutputItemParam {
    /// The streamed output items emitted by a shell tool call.
    pub fn new(
        call_id: String,
        r#type: FunctionShellCallOutputItemParamType,
        output: Vec<models::FunctionShellCallOutputContentParam>,
    ) -> FunctionShellCallOutputItemParam {
        FunctionShellCallOutputItemParam {
            call_id,
            r#type,
            output,
            id: None,
            status: None,
            max_output_length: None,
        }
    }
}
/// The type of the item. Always `shell_call_output`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum FunctionShellCallOutputItemParamType {
    #[serde(rename = "shell_call_output")]
    #[default]
    ShellCallOutput,
}


#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FunctionShellCallOutputOutcomeParam {
    #[serde(rename = "FunctionShellCallOutputTimeoutOutcomeParam")]
    FunctionShellCallOutputTimeoutOutcomeParam(
        Box<models::FunctionShellCallOutputTimeoutOutcomeParam>,
    ),
    #[serde(rename = "FunctionShellCallOutputExitOutcomeParam")]
    FunctionShellCallOutputExitOutcomeParam(Box<models::FunctionShellCallOutputExitOutcomeParam>),
}

impl Default for FunctionShellCallOutputOutcomeParam {
    fn default() -> Self {
        Self::FunctionShellCallOutputTimeoutOutcomeParam(Default::default())
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionShellCallOutputStatusEnum {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}

impl std::fmt::Display for FunctionShellCallOutputStatusEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InProgress => write!(f, "in_progress"),
            Self::Completed => write!(f, "completed"),
            Self::Incomplete => write!(f, "incomplete"),
        }
    }
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellCallOutputTimeoutOutcome {
    /// The outcome type. Always `timeout`.
    #[serde(rename = "type")]
    pub r#type: FunctionShellCallOutputTimeoutOutcomeType,
}

impl FunctionShellCallOutputTimeoutOutcome {
    /// Indicates that the shell call exceeded its configured time limit.
    pub fn new(
        r#type: FunctionShellCallOutputTimeoutOutcomeType,
    ) -> FunctionShellCallOutputTimeoutOutcome {
        FunctionShellCallOutputTimeoutOutcome { r#type }
    }
}
/// The outcome type. Always `timeout`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum FunctionShellCallOutputTimeoutOutcomeType {
    #[serde(rename = "timeout")]
    #[default]
    Timeout,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellCallOutputTimeoutOutcomeParam {
    /// The outcome type. Always `timeout`.
    #[serde(rename = "type")]
    pub r#type: FunctionShellCallOutputTimeoutOutcomeParamType,
}

impl FunctionShellCallOutputTimeoutOutcomeParam {
    /// Indicates that the shell call exceeded its configured time limit.
    pub fn new(
        r#type: FunctionShellCallOutputTimeoutOutcomeParamType,
    ) -> FunctionShellCallOutputTimeoutOutcomeParam {
        FunctionShellCallOutputTimeoutOutcomeParam { r#type }
    }
}
/// The outcome type. Always `timeout`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum FunctionShellCallOutputTimeoutOutcomeParamType {
    #[serde(rename = "timeout")]
    #[default]
    Timeout,
}


#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum FunctionShellCallStatus {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}

impl std::fmt::Display for FunctionShellCallStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InProgress => write!(f, "in_progress"),
            Self::Completed => write!(f, "completed"),
            Self::Incomplete => write!(f, "incomplete"),
        }
    }
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionShellToolParam {
    /// The type of the shell tool. Always `shell`.
    #[serde(rename = "type")]
    pub r#type: FunctionShellToolParamType,
    #[serde(
        rename = "environment",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub environment: Option<Option<Box<models::FunctionShellToolParamEnvironment>>>,
}

impl FunctionShellToolParam {
    /// A tool that allows the model to execute shell commands.
    pub fn new(r#type: FunctionShellToolParamType) -> FunctionShellToolParam {
        FunctionShellToolParam { r#type, environment: None }
    }
}
/// The type of the shell tool. Always `shell`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum FunctionShellToolParamType {
    #[serde(rename = "shell")]
    #[default]
    Shell,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalEnvironmentParam {
    /// Use a local computer environment.
    #[serde(rename = "type")]
    pub r#type: LocalEnvironmentParamType,
    /// An optional list of skills.
    #[serde(rename = "skills", skip_serializing_if = "Option::is_none")]
    pub skills: Option<Vec<models::LocalSkillParam>>,
}

impl LocalEnvironmentParam {
    pub fn new(r#type: LocalEnvironmentParamType) -> LocalEnvironmentParam {
        LocalEnvironmentParam { r#type, skills: None }
    }
}
/// Use a local computer environment.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum LocalEnvironmentParamType {
    #[serde(rename = "local")]
    #[default]
    Local,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalEnvironmentResource {
    /// The environment type. Always `local`.
    #[serde(rename = "type")]
    pub r#type: LocalEnvironmentResourceType,
}

impl LocalEnvironmentResource {
    /// Represents the use of a local environment to perform shell actions.
    pub fn new(r#type: LocalEnvironmentResourceType) -> LocalEnvironmentResource {
        LocalEnvironmentResource { r#type }
    }
}
/// The environment type. Always `local`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum LocalEnvironmentResourceType {
    #[serde(rename = "local")]
    #[default]
    Local,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalShellExecAction {
    /// The type of the local shell action. Always `exec`.
    #[serde(rename = "type")]
    pub r#type: LocalShellExecActionType,
    /// The command to run.
    #[serde(rename = "command")]
    pub command: Vec<String>,
    /// Environment variables to set for the command.
    #[serde(rename = "env")]
    pub env: std::collections::HashMap<String, String>,
    /// Optional timeout in milliseconds for the command.
    #[serde(
        rename = "timeout_ms",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub timeout_ms: Option<Option<i32>>,
    /// Optional working directory to run the command in.
    #[serde(
        rename = "working_directory",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub working_directory: Option<Option<String>>,
    /// Optional user to run the command as.
    #[serde(
        rename = "user",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user: Option<Option<String>>,
}

impl LocalShellExecAction {
    /// Execute a shell command on the server.
    pub fn new(
        r#type: LocalShellExecActionType,
        command: Vec<String>,
        env: std::collections::HashMap<String, String>,
    ) -> LocalShellExecAction {
        LocalShellExecAction {
            r#type,
            command,
            env,
            timeout_ms: None,
            working_directory: None,
            user: None,
        }
    }
}
/// The type of the local shell action. Always `exec`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum LocalShellExecActionType {
    #[serde(rename = "exec")]
    #[default]
    Exec,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalShellToolCall {
    /// The type of the local shell call. Always `local_shell_call`.
    #[serde(rename = "type")]
    pub r#type: LocalShellToolCallType,
    /// The unique ID of the local shell call.
    #[serde(rename = "id")]
    pub id: String,
    /// The unique ID of the local shell tool call generated by the model.
    #[serde(rename = "call_id")]
    pub call_id: String,
    #[serde(rename = "action")]
    pub action: Box<models::LocalShellExecAction>,
    /// The status of the local shell call.
    #[serde(rename = "status")]
    pub status: LocalShellToolCallStatus,
}

impl LocalShellToolCall {
    /// A tool call to run a command on the local shell.
    pub fn new(
        r#type: LocalShellToolCallType,
        id: String,
        call_id: String,
        action: models::LocalShellExecAction,
        status: LocalShellToolCallStatus,
    ) -> LocalShellToolCall {
        LocalShellToolCall { r#type, id, call_id, action: Box::new(action), status }
    }
}
/// The type of the local shell call. Always `local_shell_call`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum LocalShellToolCallType {
    #[serde(rename = "local_shell_call")]
    #[default]
    LocalShellCall,
}

/// The status of the local shell call.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum LocalShellToolCallStatus {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalShellToolCallOutput {
    /// The type of the local shell tool call output. Always `local_shell_call_output`.
    #[serde(rename = "type")]
    pub r#type: LocalShellToolCallOutputType,
    /// The unique ID of the local shell tool call generated by the model.
    #[serde(rename = "id")]
    pub id: String,
    /// A JSON string of the output of the local shell tool call.
    #[serde(rename = "output")]
    pub output: String,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`.
    #[serde(
        rename = "status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<Option<LocalShellToolCallOutputStatus>>,
}

impl LocalShellToolCallOutput {
    /// The output of a local shell tool call.
    pub fn new(
        r#type: LocalShellToolCallOutputType,
        id: String,
        output: String,
    ) -> LocalShellToolCallOutput {
        LocalShellToolCallOutput { r#type, id, output, status: None }
    }
}
/// The type of the local shell tool call output. Always `local_shell_call_output`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum LocalShellToolCallOutputType {
    #[serde(rename = "local_shell_call_output")]
    #[default]
    LocalShellCallOutput,
}

/// The status of the item. One of `in_progress`, `completed`, or `incomplete`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum LocalShellToolCallOutputStatus {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalShellToolParam {
    /// The type of the local shell tool. Always `local_shell`.
    #[serde(rename = "type")]
    pub r#type: LocalShellToolParamType,
}

impl LocalShellToolParam {
    /// A tool that allows the model to execute shell commands in a local environment.
    pub fn new(r#type: LocalShellToolParamType) -> LocalShellToolParam {
        LocalShellToolParam { r#type }
    }
}
/// The type of the local shell tool. Always `local_shell`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum LocalShellToolParamType {
    #[serde(rename = "local_shell")]
    #[default]
    LocalShell,
}


#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ShellCallOutcome {
    #[serde(rename = "FunctionShellCallOutputTimeoutOutcome")]
    FunctionShellCallOutputTimeoutOutcome(Box<models::FunctionShellCallOutputTimeoutOutcome>),
    #[serde(rename = "FunctionShellCallOutputExitOutcome")]
    FunctionShellCallOutputExitOutcome(Box<models::FunctionShellCallOutputExitOutcome>),
}

impl Default for ShellCallOutcome {
    fn default() -> Self {
        Self::FunctionShellCallOutputTimeoutOutcome(Default::default())
    }
}
