use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolSearchCall {
    /// The type of the item. Always `tool_search_call`.
    #[serde(rename = "type")]
    pub r#type: ToolSearchCallType,
    /// The unique ID of the tool search call item.
    #[serde(rename = "id")]
    pub id: String,
    /// The unique ID of the tool search call generated by the model.
    #[serde(rename = "call_id", deserialize_with = "Option::deserialize")]
    pub call_id: Option<String>,
    /// Whether tool search was executed by the server or by the client.
    #[serde(rename = "execution")]
    pub execution: models::ToolSearchExecutionType,
    #[serde(rename = "arguments", deserialize_with = "Option::deserialize")]
    pub arguments: Option<serde_json::Value>,
    /// The status of the tool search call item that was recorded.
    #[serde(rename = "status")]
    pub status: models::FunctionCallStatus,
    /// The identifier of the actor that created the item.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl ToolSearchCall {
    pub fn new(
        r#type: ToolSearchCallType,
        id: String,
        call_id: Option<String>,
        execution: models::ToolSearchExecutionType,
        arguments: Option<serde_json::Value>,
        status: models::FunctionCallStatus,
    ) -> ToolSearchCall {
        ToolSearchCall { r#type, id, call_id, execution, arguments, status, created_by: None }
    }
}
/// The type of the item. Always `tool_search_call`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum ToolSearchCallType {
    #[serde(rename = "tool_search_call")]
    #[default]
    ToolSearchCall,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolSearchCallItemParam {
    /// The item type. Always `tool_search_call`.
    #[serde(rename = "type")]
    pub r#type: ToolSearchCallItemParamType,
    /// The arguments supplied to the tool search call.
    #[serde(rename = "arguments")]
    pub arguments: serde_json::Value,
    /// The unique ID of this tool search call.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    /// The unique ID of the tool search call generated by the model.
    #[serde(
        rename = "call_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub call_id: Option<Option<String>>,
    /// Whether tool search was executed by the server or by the client.
    #[serde(rename = "execution", skip_serializing_if = "Option::is_none")]
    pub execution: Option<models::ToolSearchExecutionType>,
    /// The status of the tool search call.
    #[serde(
        rename = "status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<Option<models::FunctionCallItemStatus>>,
}

impl ToolSearchCallItemParam {
    pub fn new(
        r#type: ToolSearchCallItemParamType,
        arguments: serde_json::Value,
    ) -> ToolSearchCallItemParam {
        ToolSearchCallItemParam {
            r#type,
            arguments,
            id: None,
            call_id: None,
            execution: None,
            status: None,
        }
    }
}
/// The item type. Always `tool_search_call`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum ToolSearchCallItemParamType {
    #[serde(rename = "tool_search_call")]
    #[default]
    ToolSearchCall,
}


#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum ToolSearchExecutionType {
    #[serde(rename = "server")]
    #[default]
    Server,
    #[serde(rename = "client")]
    Client,
}

impl std::fmt::Display for ToolSearchExecutionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Server => write!(f, "server"),
            Self::Client => write!(f, "client"),
        }
    }
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolSearchOutput {
    /// The type of the item. Always `tool_search_output`.
    #[serde(rename = "type")]
    pub r#type: ToolSearchOutputType,
    /// The unique ID of the tool search output item.
    #[serde(rename = "id")]
    pub id: String,
    /// The unique ID of the tool search call generated by the model.
    #[serde(rename = "call_id", deserialize_with = "Option::deserialize")]
    pub call_id: Option<String>,
    /// Whether tool search was executed by the server or by the client.
    #[serde(rename = "execution")]
    pub execution: models::ToolSearchExecutionType,
    /// The loaded tool definitions returned by tool search.
    #[serde(rename = "tools")]
    pub tools: Vec<models::Tool>,
    /// The status of the tool search output item that was recorded.
    #[serde(rename = "status")]
    pub status: models::FunctionCallOutputStatusEnum,
    /// The identifier of the actor that created the item.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl ToolSearchOutput {
    pub fn new(
        r#type: ToolSearchOutputType,
        id: String,
        call_id: Option<String>,
        execution: models::ToolSearchExecutionType,
        tools: Vec<models::Tool>,
        status: models::FunctionCallOutputStatusEnum,
    ) -> ToolSearchOutput {
        ToolSearchOutput { r#type, id, call_id, execution, tools, status, created_by: None }
    }
}
/// The type of the item. Always `tool_search_output`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum ToolSearchOutputType {
    #[serde(rename = "tool_search_output")]
    #[default]
    ToolSearchOutput,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolSearchOutputItemParam {
    /// The item type. Always `tool_search_output`.
    #[serde(rename = "type")]
    pub r#type: ToolSearchOutputItemParamType,
    /// The loaded tool definitions returned by the tool search output.
    #[serde(rename = "tools")]
    pub tools: Vec<models::Tool>,
    /// The unique ID of this tool search output.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    /// The unique ID of the tool search call generated by the model.
    #[serde(
        rename = "call_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub call_id: Option<Option<String>>,
    /// Whether tool search was executed by the server or by the client.
    #[serde(rename = "execution", skip_serializing_if = "Option::is_none")]
    pub execution: Option<models::ToolSearchExecutionType>,
    /// The status of the tool search output.
    #[serde(
        rename = "status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<Option<models::FunctionCallItemStatus>>,
}

impl ToolSearchOutputItemParam {
    pub fn new(
        r#type: ToolSearchOutputItemParamType,
        tools: Vec<models::Tool>,
    ) -> ToolSearchOutputItemParam {
        ToolSearchOutputItemParam {
            r#type,
            tools,
            id: None,
            call_id: None,
            execution: None,
            status: None,
        }
    }
}
/// The item type. Always `tool_search_output`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum ToolSearchOutputItemParamType {
    #[serde(rename = "tool_search_output")]
    #[default]
    ToolSearchOutput,
}


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolSearchToolParam {
    /// The type of the tool. Always `tool_search`.
    #[serde(rename = "type")]
    pub r#type: ToolSearchToolParamType,
    /// Whether tool search is executed by the server or by the client.
    #[serde(rename = "execution", skip_serializing_if = "Option::is_none")]
    pub execution: Option<models::ToolSearchExecutionType>,
    /// Description shown to the model for a client-executed tool search tool.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// Parameter schema for a client-executed tool search tool.
    #[serde(
        rename = "parameters",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parameters: Option<Option<serde_json::Value>>,
}

impl ToolSearchToolParam {
    /// Hosted or BYOT tool search configuration for deferred tools.
    pub fn new(r#type: ToolSearchToolParamType) -> ToolSearchToolParam {
        ToolSearchToolParam { r#type, execution: None, description: None, parameters: None }
    }
}
/// The type of the tool. Always `tool_search`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub(crate) enum ToolSearchToolParamType {
    #[serde(rename = "tool_search")]
    #[default]
    ToolSearch,
}

