/// Flutter theme over the generated design tokens (`slab_tokens.g.dart`, the
/// one-way export from `packages/slab-components/src/styles/globals.css`).
///
/// Hand-written on purpose: the token VALUES must never be hand-edited (they
/// are regenerated by `bun run gen:mobile` and drift-guarded in CI), but how
/// they map onto Material/Flutter concepts is app code. Compound CSS values
/// the exporter cannot compile (box shadows, color-mix glass, the soft-in
/// animation) are expressed natively here — e.g. `--ease-out-expo` becomes
/// `SlabMetrics.easeOutExpo` (a `Cubic`), and elevation uses Material shadows.
library;

import 'package:flutter/material.dart';

import 'slab_tokens.g.dart';

/// Bespoke tokens with no Material equivalent, resolved per brightness
/// (chat bubbles, tool surfaces, brand accents).
@immutable
class SlabExtras extends ThemeExtension<SlabExtras> {
  const SlabExtras({
    required this.aiBubble,
    required this.aiBubbleForeground,
    required this.userBubble,
    required this.userBubbleForeground,
    required this.aiTool,
    required this.aiToolForeground,
    required this.brandGold,
    required this.success,
    required this.successForeground,
    required this.sidebar,
  });

  final Color aiBubble;
  final Color aiBubbleForeground;
  final Color userBubble;
  final Color userBubbleForeground;
  final Color aiTool;
  final Color aiToolForeground;
  final Color brandGold;
  final Color success;
  final Color successForeground;
  final Color sidebar;

  static const light = SlabExtras(
    aiBubble: SlabTokensLight.aiBubble,
    aiBubbleForeground: SlabTokensLight.aiBubbleForeground,
    userBubble: SlabTokensLight.userBubble,
    userBubbleForeground: SlabTokensLight.userBubbleForeground,
    aiTool: SlabTokensLight.aiTool,
    aiToolForeground: SlabTokensLight.aiToolForeground,
    brandGold: SlabTokensLight.brandGold,
    success: SlabTokensLight.success,
    successForeground: SlabTokensLight.successForeground,
    sidebar: SlabTokensLight.sidebar,
  );

  static const dark = SlabExtras(
    aiBubble: SlabTokensDark.aiBubble,
    aiBubbleForeground: SlabTokensDark.aiBubbleForeground,
    userBubble: SlabTokensDark.userBubble,
    userBubbleForeground: SlabTokensDark.userBubbleForeground,
    aiTool: SlabTokensDark.aiTool,
    aiToolForeground: SlabTokensDark.aiToolForeground,
    brandGold: SlabTokensDark.brandGold,
    success: SlabTokensDark.success,
    successForeground: SlabTokensDark.successForeground,
    sidebar: SlabTokensDark.sidebar,
  );

  @override
  SlabExtras copyWith({ThemeExtension<SlabExtras>? other}) => this;

  @override
  SlabExtras lerp(ThemeExtension<SlabExtras>? other, double t) => this;
}

/// The shared "soft-in" curve (`--ease-out-expo`, also the default transition
/// timing in globals.css).
final Cubic slabEaseOutExpo = SlabMetrics.easeOutExpo;
const int slabTransitionMs = 180; // --default-transition-duration

TextTheme _textTheme(Color foreground, Color mutedForeground) {
  const familyFallback = SlabMetrics.fontSans;
  return TextTheme(
    displaySmall: TextStyle(fontSize: SlabMetrics.radius2xl /* 24 */, color: foreground, letterSpacing: SlabMetrics.trackingDisplay * 24, fontFamilyFallback: familyFallback),
    titleMedium: TextStyle(fontSize: SlabMetrics.textBody + 3, color: foreground, fontFamilyFallback: familyFallback),
    bodyMedium: TextStyle(fontSize: SlabMetrics.textBody, height: 1.5, color: foreground, fontFamilyFallback: familyFallback),
    bodySmall: TextStyle(fontSize: SlabMetrics.textCaption, height: 1.45, color: mutedForeground, fontFamilyFallback: familyFallback),
    labelSmall: TextStyle(fontSize: SlabMetrics.textMicro, letterSpacing: SlabMetrics.trackingEyebrow * SlabMetrics.textMicro, color: mutedForeground, fontFamilyFallback: familyFallback),
    labelLarge: TextStyle(fontSize: SlabMetrics.textLabel, color: foreground, fontFamilyFallback: familyFallback),
  );
}

ThemeData buildSlabTheme(Brightness brightness) {
  final light = brightness == Brightness.light;
  final colorScheme = ColorScheme(
    brightness: brightness,
    primary: light ? SlabTokensLight.primary : SlabTokensDark.primary,
    onPrimary: light ? SlabTokensLight.primaryForeground : SlabTokensDark.primaryForeground,
    secondary: light ? SlabTokensLight.secondary : SlabTokensDark.secondary,
    onSecondary: light ? SlabTokensLight.secondaryForeground : SlabTokensDark.secondaryForeground,
    error: light ? SlabTokensLight.destructive : SlabTokensDark.destructive,
    onError: light ? SlabTokensLight.destructiveForeground : SlabTokensDark.destructiveForeground,
    surface: light ? SlabTokensLight.background : SlabTokensDark.background,
    onSurface: light ? SlabTokensLight.foreground : SlabTokensDark.foreground,
    onSurfaceVariant: light ? SlabTokensLight.mutedForeground : SlabTokensDark.mutedForeground,
    surfaceContainerHighest: light ? SlabTokensLight.muted : SlabTokensDark.muted,
    surfaceContainer: light ? SlabTokensLight.secondary : SlabTokensDark.secondary,
    surfaceContainerLow: light ? SlabTokensLight.card : SlabTokensDark.card,
    surfaceContainerLowest: light ? SlabTokensLight.card : SlabTokensDark.card,
    surfaceContainerHigh: light ? SlabTokensLight.accent : SlabTokensDark.accent,
    outline: light ? SlabTokensLight.border : SlabTokensDark.border,
    outlineVariant: light ? SlabTokensLight.input : SlabTokensDark.input,
    tertiary: light ? SlabTokensLight.brandGold : SlabTokensDark.brandGold,
    onTertiary: light ? SlabTokensLight.background : SlabTokensDark.background,
  );

  final foreground = colorScheme.onSurface;
  final mutedForeground = colorScheme.onSurfaceVariant;

  return ThemeData(
    useMaterial3: true,
    colorScheme: colorScheme,
    scaffoldBackgroundColor: colorScheme.surface,
    splashFactory: InkSparkle.splashFactory,
    extensions: [light ? SlabExtras.light : SlabExtras.dark],
    textTheme: _textTheme(foreground, mutedForeground),
    inputDecorationTheme: InputDecorationTheme(
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(SlabMetrics.radiusMd),
        borderSide: BorderSide(color: colorScheme.outline),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(SlabMetrics.radiusMd),
        borderSide: BorderSide(color: colorScheme.primary, width: 1.5),
      ),
      contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      isDense: true,
    ),
    filledButtonTheme: FilledButtonThemeData(
      style: FilledButton.styleFrom(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(SlabMetrics.radiusMd)),
        textStyle: const TextStyle(fontSize: SlabMetrics.textBody),
      ),
    ),
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: OutlinedButton.styleFrom(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(SlabMetrics.radiusMd)),
        textStyle: const TextStyle(fontSize: SlabMetrics.textBody),
      ),
    ),
    chipTheme: ChipThemeData(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(SlabMetrics.radiusSm)),
      labelStyle: const TextStyle(fontSize: SlabMetrics.textCaption),
      side: BorderSide(color: colorScheme.outline),
    ),
    dialogTheme: DialogThemeData(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(SlabMetrics.radiusLg)),
      backgroundColor: colorScheme.surfaceContainerLowest,
    ),
    snackBarTheme: SnackBarThemeData(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(SlabMetrics.radiusSm)),
      behavior: SnackBarBehavior.floating,
    ),
    listTileTheme: ListTileThemeData(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(SlabMetrics.radiusMd)),
      titleTextStyle: TextStyle(fontSize: SlabMetrics.textBody, color: foreground),
      subtitleTextStyle: TextStyle(fontSize: SlabMetrics.textCaption, color: mutedForeground),
    ),
    dividerTheme: DividerThemeData(color: colorScheme.outline, thickness: 1, space: 1),
  );
}

/// `Theme.of(context).extension<SlabExtras>()!` convenience.
SlabExtras slabExtras(BuildContext context) => Theme.of(context).extension<SlabExtras>()!;
