use crate::openai::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EasyInputMessage {
    /// The role of the message input. One of `user`, `assistant`, `system`, or `developer`.
    #[serde(rename = "role")]
    pub role: CommonMessageRole,
    #[serde(rename = "content")]
    pub content: Box<models::EasyInputMessageContent>,
    #[serde(
        rename = "phase",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phase: Option<Option<models::MessagePhase>>,
    /// The type of the message input. Always `message`.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<CommonMessageType>,
}

impl EasyInputMessage {
    /// A message input to the model with a role indicating instruction following hierarchy. Instructions given with the `developer` or `system` role take precedence over instructions given with the `user` role. Messages with the `assistant` role are presumed to have been generated by the model in previous interactions.
    pub fn new(
        role: CommonMessageRole,
        content: models::EasyInputMessageContent,
    ) -> EasyInputMessage {
        EasyInputMessage { role, content: Box::new(content), phase: None, r#type: None }
    }
}
/// The role of the message input. One of `user`, `assistant`, `system`, or `developer`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CommonMessageRole {
    #[serde(rename = "user")]
    #[default]
    User,
    #[serde(rename = "assistant")]
    Assistant,
    #[serde(rename = "system")]
    System,
    #[serde(rename = "developer")]
    Developer,
}

/// The type of the message input. Always `message`.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CommonMessageType {
    #[serde(rename = "message")]
    #[default]
    Message,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EasyInputMessageContent {
    /// A text input to the model.
    TextInput(String),
    /// A list of one or many input items to the model, containing different content  types.
    InputMessageContentList(Vec<models::InputContent>),
}

impl Default for EasyInputMessageContent {
    fn default() -> Self {
        Self::TextInput(Default::default())
    }
}

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum MessagePhase {
    #[serde(rename = "commentary")]
    #[default]
    Commentary,
    #[serde(rename = "final_answer")]
    FinalAnswer,
}

impl std::fmt::Display for MessagePhase {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Commentary => write!(f, "commentary"),
            Self::FinalAnswer => write!(f, "final_answer"),
        }
    }
}

pub type MessagePhase2 = MessagePhase;
