use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EasyInputMessage {
    /// The role of the message input. One of `user`, `assistant`, `system`, or `developer`.
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "content")]
    pub content: Box<models::EasyInputMessageContent>,
    #[serde(
        rename = "phase",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phase: Option<Option<models::MessagePhase>>,
    /// The type of the message input. Always `message`.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl EasyInputMessage {
    /// A message input to the model with a role indicating instruction following hierarchy. Instructions given with the `developer` or `system` role take precedence over instructions given with the `user` role. Messages with the `assistant` role are presumed to have been generated by the model in previous interactions.
    pub fn new(role: Role, content: models::EasyInputMessageContent) -> EasyInputMessage {
        EasyInputMessage { role, content: Box::new(content), phase: None, r#type: None }
    }
}
/// The role of the message input. One of `user`, `assistant`, `system`, or `developer`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub(crate) enum Role {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
    #[serde(rename = "system")]
    System,
    #[serde(rename = "developer")]
    Developer,
}

impl Default for Role {
    fn default() -> Role {
        Self::User
    }
}
/// The type of the message input. Always `message`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub(crate) enum Type {
    #[serde(rename = "message")]
    Message,
}

impl Default for Type {
    fn default() -> Type {
        Self::Message
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EasyInputMessageContent {
    /// A text input to the model.
    TextInput(String),
    /// A list of one or many input items to the model, containing different content  types.
    InputMessageContentList(Vec<models::InputContent>),
}

impl Default for EasyInputMessageContent {
    fn default() -> Self {
        Self::TextInput(Default::default())
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MessagePhase {
    #[serde(rename = "commentary")]
    Commentary,
    #[serde(rename = "final_answer")]
    FinalAnswer,
}

impl std::fmt::Display for MessagePhase {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Commentary => write!(f, "commentary"),
            Self::FinalAnswer => write!(f, "final_answer"),
        }
    }
}

impl Default for MessagePhase {
    fn default() -> MessagePhase {
        Self::Commentary
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MessagePhase2 {
    #[serde(rename = "commentary")]
    Commentary,
    #[serde(rename = "final_answer")]
    FinalAnswer,
}

impl std::fmt::Display for MessagePhase2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Commentary => write!(f, "commentary"),
            Self::FinalAnswer => write!(f, "final_answer"),
        }
    }
}

impl Default for MessagePhase2 {
    fn default() -> MessagePhase2 {
        Self::Commentary
    }
}
