use crate::openai::models;
use serde::{Deserialize, Serialize};

/// CompactionBody : A compaction item generated by the [`v1/responses/compact` API](/docs/api-reference/responses/compact).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompactionBody {
    /// The type of the item. Always `compaction`.
    #[serde(rename = "type")]
    pub r#type: CompactionBodyType,
    /// The unique ID of the compaction item.
    #[serde(rename = "id")]
    pub id: String,
    /// The encrypted content that was produced by compaction.
    #[serde(rename = "encrypted_content")]
    pub encrypted_content: String,
    /// The identifier of the actor that created the item.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}

impl CompactionBody {
    /// A compaction item generated by the [`v1/responses/compact` API](/docs/api-reference/responses/compact).
    pub fn new(
        r#type: CompactionBodyType,
        id: String,
        encrypted_content: String,
    ) -> CompactionBody {
        CompactionBody { r#type, id, encrypted_content, created_by: None }
    }
}

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CompactionBodyType {
    #[serde(rename = "compaction")]
    #[default]
    Compaction,
}

/// CompactionSummaryItemParam : A compaction item generated by the [`v1/responses/compact` API](/docs/api-reference/responses/compact).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompactionSummaryItemParam {
    /// The type of the item. Always `compaction`.
    #[serde(rename = "type")]
    pub r#type: CompactionBodyType,
    /// The encrypted content of the compaction summary.
    #[serde(rename = "encrypted_content")]
    pub encrypted_content: String,
    /// The ID of the compaction item.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
}

impl CompactionSummaryItemParam {
    /// A compaction item generated by the [`v1/responses/compact` API](/docs/api-reference/responses/compact).
    pub fn new(
        r#type: CompactionBodyType,
        encrypted_content: String,
    ) -> CompactionSummaryItemParam {
        CompactionSummaryItemParam { r#type, encrypted_content, id: None }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ComparisonFilterValueOneOfInner {
    String(String),
    Number(f64),
}

impl Default for ComparisonFilterValueOneOfInner {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

/// ComparisonFilterValue : The value to compare against the attribute key; supports string, number, or boolean types.
/// The value to compare against the attribute key; supports string, number, or boolean types.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ComparisonFilterValue {
    String(String),
    Number(f64),
    Boolean(bool),
    ArrayVecComparisonFilterValueOneOfInner(Vec<models::ComparisonFilterValueOneOfInner>),
}

impl Default for ComparisonFilterValue {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ComparisonFilterType {
    #[serde(rename = "eq")]
    #[default]
    Eq,
    #[serde(rename = "ne")]
    Ne,
    #[serde(rename = "gt")]
    Gt,
    #[serde(rename = "gte")]
    Gte,
    #[serde(rename = "lt")]
    Lt,
    #[serde(rename = "lte")]
    Lte,
    #[serde(rename = "in")]
    In,
    #[serde(rename = "nin")]
    Nin,
}

/// ComparisonFilter : A filter used to compare a specified attribute key to a given value using a defined comparison operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComparisonFilter {
    /// Specifies the comparison operator: `eq`, `ne`, `gt`, `gte`, `lt`, `lte`, `in`, `nin`. - `eq`: equals - `ne`: not equal - `gt`: greater than - `gte`: greater than or equal - `lt`: less than - `lte`: less than or equal - `in`: in - `nin`: not in
    #[serde(rename = "type")]
    pub r#type: ComparisonFilterType,
    /// The key to compare against the value.
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: Box<models::ComparisonFilterValue>,
}

impl ComparisonFilter {
    /// A filter used to compare a specified attribute key to a given value using a defined comparison operation.
    pub fn new(
        r#type: ComparisonFilterType,
        key: String,
        value: models::ComparisonFilterValue,
    ) -> ComparisonFilter {
        ComparisonFilter { r#type, key, value: Box::new(value) }
    }
}
